vocab_db = {
    "Package 1: The Absolute Core (Top 50)": [
        {"lemma": "sum, esse, fuī, futūrus", "meaning": "to be, exist"},
        {"lemma": "et", "meaning": "and"},
        {"lemma": "in (+ acc. / + abl.)", "meaning": "in, into, on, against"},
        {"lemma": "que (enclitic)", "meaning": "and"},
        {"lemma": "quī, quae, quod", "meaning": "who, which, what, that"},
        {"lemma": "nōn", "meaning": "not"},
        {"lemma": "hic, haec, hoc", "meaning": "this, these"},
        {"lemma": "ille, illa, illud", "meaning": "that, those"},
        {"lemma": "tū, tuī, tibi, tē", "meaning": "you"},
        {"lemma": "cum", "meaning": "with, when, since, although"},
        {"lemma": "ego, meī, mihi, mē", "meaning": "I, me"},
        {"lemma": "ad (+ acc.)", "meaning": "to, toward, at"},
        {"lemma": "suus, -a, -um", "meaning": "his, her, its, their (own)"},
        {"lemma": "is, ea, id", "meaning": "he, she, it, this, that"},
        {"lemma": "nec / neque", "meaning": "and not, nor"},
        {"lemma": "sed", "meaning": "but"},
        {"lemma": "omnis, omne", "meaning": "all, every"},
        {"lemma": "ā / ab (+ abl.)", "meaning": "from, away from, by"},
        {"lemma": "deus, deī, m.", "meaning": "god"},
        {"lemma": "rēs, reī, f.", "meaning": "thing, matter, business"},
        {"lemma": "iam", "meaning": "now, already"},
        {"lemma": "dō, dare, dedī, datus", "meaning": "to give"},
        {"lemma": "atque / ac", "meaning": "and, and also"},
        {"lemma": "alius, alia, aliud", "meaning": "other, another"},
        {"lemma": "multus, -a, -um", "meaning": "much, many"},
        {"lemma": "magnus, -a, -um", "meaning": "great, big, large"},
        {"lemma": "ē / ex (+ abl.)", "meaning": "out of, from"},
        {"lemma": "suī, sibi, sē", "meaning": "himself, herself, itself, themselves"},
        {"lemma": "habeō, habēre, habuī, habitus", "meaning": "to have, hold"},
        {"lemma": "animus, animī, m.", "meaning": "mind, spirit, soul"},
        {"lemma": "noster, nostra, nostrum", "meaning": "our, ours"},
        {"lemma": "possum, posse, potuī", "meaning": "to be able, can"},
        {"lemma": "nihil / nīl", "meaning": "nothing"},
        {"lemma": "videō, vidēre, vīdī, vīsus", "meaning": "to see"},
        {"lemma": "dē (+ abl.)", "meaning": "about, concerning, down from"},
        {"lemma": "per (+ acc.)", "meaning": "through, along, by means of"},
        {"lemma": "faciō, facere, fēcī, factus", "meaning": "to make, do"},
        {"lemma": "tuus, -a, -um", "meaning": "your, yours"},
        {"lemma": "locus, locī, m.", "meaning": "place, location"},
        {"lemma": "bonus, -a, -um", "meaning": "good"},
        {"lemma": "tempus, temporis, n.", "meaning": "time"},
        {"lemma": "dīcō, dīcere, dīxī, dictus", "meaning": "to say, speak, tell"},
        {"lemma": "nullus, -a, -um", "meaning": "no, none"},
        {"lemma": "homō, hominis, m.", "meaning": "human, man, person"},
        {"lemma": "urbs, urbis, f.", "meaning": "city"},
        {"lemma": "diēs, diēī, m./f.", "meaning": "day"},
        {"lemma": "manus, manūs, f.", "meaning": "hand, band of men"},
        {"lemma": "pater, patris, m.", "meaning": "father"},
        {"lemma": "causa, causae, f.", "meaning": "cause, reason"},
        {"lemma": "volō, velle, voluī", "meaning": "to want, wish"}
    ],
    
    "Package 2: Action & Motion (Verbs I)": [
        {"lemma": "veniō, venīre, vēnī, ventus", "meaning": "to come"},
        {"lemma": "eō, īre, iī, itus", "meaning": "to go"},
        {"lemma": "ferō, ferre, tulī, lātus", "meaning": "to bear, carry, bring"},
        {"lemma": "mittō, mittere, mīsī, missus", "meaning": "to send"},
        {"lemma": "relinquō, relinquere, relīquī, relictus", "meaning": "to leave behind, abandon"},
        {"lemma": "pōnō, pōnere, posuī, positus", "meaning": "to put, place"},
        {"lemma": "petō, petere, petīvī, petītus", "meaning": "to seek, attack, head for"},
        {"lemma": "fugiō, fugere, fūgī, fugitus", "meaning": "to flee, run away"},
        {"lemma": "currō, currere, cucurrī, cursus", "meaning": "to run"},
        {"lemma": "cadō, cadere, cecidī, cāsus", "meaning": "to fall"},
        {"lemma": "iaciō, iacere, iēcī, iactus", "meaning": "to throw"},
        {"lemma": "capiō, capere, cēpī, captus", "meaning": "to take, capture"},
        {"lemma": "rapiō, rapere, rapuī, raptus", "meaning": "to snatch, seize"},
        {"lemma": "dūcō, dūcere, dūxī, ductus", "meaning": "to lead"},
        {"lemma": "trahō, trahere, trāxī, tractus", "meaning": "to drag, draw"},
        {"lemma": "pellō, pellere, pepulī, pulsus", "meaning": "to drive, push"},
        {"lemma": "vincō, vincere, vīcī, victus", "meaning": "to conquer, win"},
        {"lemma": "stō, stāre, stetī, status", "meaning": "to stand"},
        {"lemma": "ambulō, ambulāre, ambulāvī, ambulātus", "meaning": "to walk"},
        {"lemma": "properō, properāre, properāvī", "meaning": "to hurry, hasten"},
        {"lemma": "maneō, manēre, mānsī, mānsus", "meaning": "to remain, stay"},
        {"lemma": "ascendō, ascendere, ascendī", "meaning": "to climb, ascend"},
        {"lemma": "dēscendō, dēscendere, dēscendī", "meaning": "to climb down, descend"},
        {"lemma": "errō, errāre, errāvī, errātus", "meaning": "to wander, make a mistake"},
        {"lemma": "moveō, movēre, mōvī, mōtus", "meaning": "to move"},
        {"lemma": "vīvō, vīvere, vīxī, vīctus", "meaning": "to live"},
        {"lemma": "necō, necāre, necāvī, necātus", "meaning": "to kill"},
        {"lemma": "interficiō, interficere, interfēcī", "meaning": "to kill, destroy"},
        {"lemma": "pugnō, pugnāre, pugnāvī, pugnātus", "meaning": "to fight"},
        {"lemma": "oppugnō, oppugnāre, oppugnāvī", "meaning": "to attack"},
        {"lemma": "aedificō, aedificāre, aedificāvī", "meaning": "to build"},
        {"lemma": "nāvigō, nāvigāre, nāvigāvī", "meaning": "to sail"},
        {"lemma": "portō, portāre, portāvī, portātus", "meaning": "to carry"},
        {"lemma": "iubeō, iubēre, iussī, iussus", "meaning": "to order, command"},
        {"lemma": "pāreō, pārēre, pāruī (+ dat.)", "meaning": "to obey"},
        {"lemma": "cēdō, cēdere, cessī, cessus", "meaning": "to yield, give way, go"},
        {"lemma": "quaerō, quaerere, quaesīvī, quaesītus", "meaning": "to search for, ask, seek"},
        {"lemma": "inveniō, invenīre, invēnī, inventus", "meaning": "to find, discover"},
        {"lemma": "perdō, perdere, perdidī, perditus", "meaning": "to destroy, lose"},
        {"lemma": "teneō, tenēre, tenuī, tentus", "meaning": "to hold, keep"},
        {"lemma": "retineō, retinēre, retinuī", "meaning": "to hold back, retain"},
        {"lemma": "claudō, claudere, clausī, clausus", "meaning": "to close, shut"},
        {"lemma": "aperiō, aperīre, aperuī, apertus", "meaning": "to open"},
        {"lemma": "tegō, tegere, tēxī, tēctus", "meaning": "to cover, hide"},
        {"lemma": "frangō, frangere, frēgī, frāctus", "meaning": "to break"},
        {"lemma": "rumpō, rumpere, rūpī, ruptus", "meaning": "to burst, break"},
        {"lemma": "vertō, vertere, vertī, versus", "meaning": "to turn"},
        {"lemma": "volvō, volvere, volvī, volūtus", "meaning": "to roll, turn over"},
        {"lemma": "premō, premere, pressī, pressus", "meaning": "to press, crush"},
        {"lemma": "tangō, tangere, tetigī, tāctus", "meaning": "to touch"}
    ],
    
    "Package 3: Mind, Senses & Speech (Verbs II)": [
        {"lemma": "audiō, audīre, audīvī, audītus", "meaning": "to hear, listen"},
        {"lemma": "sentiō, sentīre, sēnsī, sēnsus", "meaning": "to feel, perceive"},
        {"lemma": "sciō, scīre, scīvī, scītus", "meaning": "to know"},
        {"lemma": "nesciō, nescīre, nescīvī", "meaning": "to not know"},
        {"lemma": "putō, putāre, putāvī, putātus", "meaning": "to think"},
        {"lemma": "crēdō, crēdere, crēdidī (+ dat.)", "meaning": "to believe, trust"},
        {"lemma": "spērō, spērāre, spērāvī", "meaning": "to hope"},
        {"lemma": "timeō, timēre, timuī", "meaning": "to fear, be afraid"},
        {"lemma": "terreō, terrēre, terruī, territus", "meaning": "to frighten, terrify"},
        {"lemma": "gaudeō, gaudēre, gavīsus sum", "meaning": "to rejoice, be glad"},
        {"lemma": "rīdeō, rīdēre, rīsī, rīsus", "meaning": "to laugh, smile"},
        {"lemma": "fleō, flēre, flēvī, flētus", "meaning": "to weep, cry"},
        {"lemma": "doleō, dolēre, doluī", "meaning": "to suffer, grieve, hurt"},
        {"lemma": "mīror, mīrārī, mīrātus sum", "meaning": "to wonder at, admire"},
        {"lemma": "soleō, solēre, solitus sum", "meaning": "to be accustomed to, usually"},
        {"lemma": "cupiō, cupere, cupīvī, cupītus", "meaning": "to desire, want"},
        {"lemma": "amō, amāre, amāvī, amātus", "meaning": "to love, like"},
        {"lemma": "placeō, placēre, placuī (+ dat.)", "meaning": "to please"},
        {"lemma": "licet, licēre, licuit", "meaning": "it is permitted, allowed"},
        {"lemma": "decet, decēre, decuit", "meaning": "it is fitting, proper"},
        {"lemma": "oportet, oportēre, oportuit", "meaning": "it is necessary, one ought"},
        {"lemma": "rogō, rogāre, rogāvī, rogātus", "meaning": "to ask"},
        {"lemma": "ōrō, ōrāre, ōrāvī, ōrātus", "meaning": "to pray, beg, plead"},
        {"lemma": "vocō, vocāre, vocāvī, vocātus", "meaning": "to call"},
        {"lemma": "clāmō, clamāre, clāmāvī", "meaning": "to shout"},
        {"lemma": "respondeō, respondēre, respondī", "meaning": "to answer, reply"},
        {"lemma": "nūntiō, nūntiāre, nūntiāvī", "meaning": "to announce, report"},
        {"lemma": "mōnstrō, monstrāre, monstrāvī", "meaning": "to show, point out"},
        {"lemma": "doceō, docēre, docuī, doctus", "meaning": "to teach"},
        {"lemma": "discō, discere, didicī", "meaning": "to learn"},
        {"lemma": "legō, legere, lēgī, lēctus", "meaning": "to read, choose, gather"},
        {"lemma": "scrībō, scrībere, scrīpsī, scrīptus", "meaning": "to write"},
        {"lemma": "canō, canere, cecinī, cantus", "meaning": "to sing"},
        {"lemma": "cantō, cantāre, cantāvī", "meaning": "to sing, chant"},
        {"lemma": "moneō, monēre, monuī, monitus", "meaning": "to warn, advise"},
        {"lemma": "cōnsulō, cōnsulere, cōnsuluī", "meaning": "to consult, consider"},
        {"lemma": "statuō, statuere, statuī", "meaning": "to decide, set up"},
        {"lemma": "cōnstituō, cōnstituere, cōnstituī", "meaning": "to decide, establish"},
        {"lemma": "iūdicō, iūdicāre, iūdicāvī", "meaning": "to judge, decide"},
        {"lemma": "arbitror, arbitrārī, arbitrātus sum", "meaning": "to judge, think"},
        {"lemma": "cōgitō, cōgitāre, cōgitāvī", "meaning": "to think, consider"},
        {"lemma": "meminī, meminisse", "meaning": "to remember"},
        {"lemma": "oblīvīscor, oblīvīscī, oblītus sum", "meaning": "to forget"},
        {"lemma": "īgnōscō, ignōscere, ignōvī (+ dat.)", "meaning": "to forgive, pardon"},
        {"lemma": "imperō, imperāre, imperāvī (+ dat.)", "meaning": "to command, order"},
        {"lemma": "vetō, vetāre, vetuī, vetitus", "meaning": "to forbid"},
        {"lemma": "suādeō, suādēre, suāsī (+ dat.)", "meaning": "to urge, recommend"},
        {"lemma": "persuādeō, persuādēre, persuāsī", "meaning": "to persuade"},
        {"lemma": "postulō, postulāre, postulāvī", "meaning": "to demand"},
        {"lemma": "hortor, hortārī, hortātus sum", "meaning": "to urge, encourage"}
    ],
    
    "Package 4: People, Family & The Body (Nouns I)": [
        {"lemma": "māter, mātris, f.", "meaning": "mother"},
        {"lemma": "frāter, frātris, m.", "meaning": "brother"},
        {"lemma": "soror, sorōris, f.", "meaning": "sister"},
        {"lemma": "fīlius, fīliī, m.", "meaning": "son"},
        {"lemma": "fīlia, fīliae, f.", "meaning": "daughter"},
        {"lemma": "puer, puerī, m.", "meaning": "boy"},
        {"lemma": "puella, puellae, f.", "meaning": "girl"},
        {"lemma": "vir, virī, m.", "meaning": "man, husband"},
        {"lemma": "fēmina, fēminae, f.", "meaning": "woman"},
        {"lemma": "uxor, uxōris, f.", "meaning": "wife"},
        {"lemma": "marītus, maritī, m.", "meaning": "husband"},
        {"lemma": "īnfāns, īnfantis, m./f.", "meaning": "infant, baby"},
        {"lemma": "iuvenis, iuvenis, m.", "meaning": "young man, youth"},
        {"lemma": "senex, senis, m.", "meaning": "old man"},
        {"lemma": "avus, avī, m.", "meaning": "grandfather"},
        {"lemma": "dominus, dominī, m.", "meaning": "master, lord"},
        {"lemma": "domina, dominae, f.", "meaning": "mistress, lady"},
        {"lemma": "servus, servī, m.", "meaning": "slave"},
        {"lemma": "ancilla, ancillae, f.", "meaning": "slave-girl"},
        {"lemma": "amīcus, amīcī, m.", "meaning": "friend"},
        {"lemma": "amīca, amīcae, f.", "meaning": "female friend, girlfriend"},
        {"lemma": "comes, comitis, m./f.", "meaning": "companion, comrade"},
        {"lemma": "socius, sociī, m.", "meaning": "ally, comrade"},
        {"lemma": "hospes, hospitis, m./f.", "meaning": "guest, host, stranger"},
        {"lemma": "magister, magistrī, m.", "meaning": "teacher, master"},
        {"lemma": "discipulus, discipulī, m.", "meaning": "student, pupil"},
        {"lemma": "caput, capitis, n.", "meaning": "head"},
        {"lemma": "oculus, oculī, m.", "meaning": "eye"},
        {"lemma": "ōs, ōris, n.", "meaning": "mouth, face"},
        {"lemma": "auris, auris, f.", "meaning": "ear"},
        {"lemma": "dēns, dentis, m.", "meaning": "tooth"},
        {"lemma": "vultus, vultūs, m.", "meaning": "face, expression"},
        {"lemma": "frōns, frontis, f.", "meaning": "forehead, front"},
        {"lemma": "pectus, pectoris, n.", "meaning": "chest, breast, heart"},
        {"lemma": "cor, cordis, n.", "meaning": "heart"},
        {"lemma": "tergum, tergī, n.", "meaning": "back, rear"},
        {"lemma": "venter, ventris, m.", "meaning": "stomach, belly"},
        {"lemma": "bracchium, bracchiī, n.", "meaning": "arm"},
        {"lemma": "pēs, pedis, m.", "meaning": "foot"},
        {"lemma": "digitus, digitī, m.", "meaning": "finger, toe"},
        {"lemma": "crūs, crūris, n.", "meaning": "leg"},
        {"lemma": "sanguis, sanguinis, m.", "meaning": "blood"},
        {"lemma": "os, ossis, n.", "meaning": "bone"},
        {"lemma": "cutis, cutis, f.", "meaning": "skin"},
        {"lemma": "vulnus, vulneris, n.", "meaning": "wound"},
        {"lemma": "morbus, morbī, m.", "meaning": "disease, illness"},
        {"lemma": "vīta, vītae, f.", "meaning": "life"},
        {"lemma": "salūs, salūtis, f.", "meaning": "health, safety, greeting"},
        {"lemma": "lētum, lētī, n.", "meaning": "death, ruin"},
        {"lemma": "fūnus, fūneris, n.", "meaning": "funeral, death"}
    ],
    
    "Package 5: Nature, Space & Time (Nouns II)": [
        {"lemma": "terra, terrae, f.", "meaning": "earth, land, ground"},
        {"lemma": "caelum, caelī, n.", "meaning": "sky, heaven"},
        {"lemma": "sōl, sōlis, m.", "meaning": "sun"},
        {"lemma": "lūna, lūnae, f.", "meaning": "moon"},
        {"lemma": "stēlla, stēllae, f.", "meaning": "star"},
        {"lemma": "astrum, astrī, n.", "meaning": "star, constellation"},
        {"lemma": "mare, maris, n.", "meaning": "sea"},
        {"lemma": "aqua, aquae, f.", "meaning": "water"},
        {"lemma": "flūmen, flūminis, n.", "meaning": "river"},
        {"lemma": "amnis, amnis, m.", "meaning": "river, stream"},
        {"lemma": "unda, undae, f.", "meaning": "wave, water"},
        {"lemma": "fōns, fontis, m.", "meaning": "spring, fountain"},
        {"lemma": "ignis, ignis, m.", "meaning": "fire"},
        {"lemma": "flamma, flammae, f.", "meaning": "flame"},
        {"lemma": "ventus, ventī, m.", "meaning": "wind"},
        {"lemma": "aura, aurae, f.", "meaning": "breeze, air"},
        {"lemma": "tempestās, tempestātis, f.", "meaning": "storm, weather"},
        {"lemma": "nūbēs, nūbis, f.", "meaning": "cloud"},
        {"lemma": "imber, imbris, m.", "meaning": "rain, rainstorm"},
        {"lemma": "nix, nivis, f.", "meaning": "snow"},
        {"lemma": "hiems, hiemis, f.", "meaning": "winter"},
        {"lemma": "aestās, aestātis, f.", "meaning": "summer"},
        {"lemma": "vēr, vēris, n.", "meaning": "spring (season)"},
        {"lemma": "autumnus, autumnī, m.", "meaning": "autumn, fall"},
        {"lemma": "annus, annī, m.", "meaning": "year"},
        {"lemma": "mēnsis, mēnsis, m.", "meaning": "month"},
        {"lemma": "nox, noctis, f.", "meaning": "night"},
        {"lemma": "hōra, hōrae, f.", "meaning": "hour"},
        {"lemma": "mōns, montis, m.", "meaning": "mountain"},
        {"lemma": "collis, collis, m.", "meaning": "hill"},
        {"lemma": "vallis, vallis, f.", "meaning": "valley"},
        {"lemma": "campus, campī, m.", "meaning": "plain, field"},
        {"lemma": "silva, silvae, f.", "meaning": "forest, woods"},
        {"lemma": "nemus, nemoris, n.", "meaning": "grove, wood"},
        {"lemma": "arbor, arboris, f.", "meaning": "tree"},
        {"lemma": "flōs, flōris, m.", "meaning": "flower"},
        {"lemma": "herba, herbae, f.", "meaning": "grass, plant"},
        {"lemma": "saxum, saxī, n.", "meaning": "rock, stone"},
        {"lemma": "lapis, lapidis, m.", "meaning": "stone"},
        {"lemma": "harēna, harenae, f.", "meaning": "sand"},
        {"lemma": "pulvis, pulveris, m.", "meaning": "dust"},
        {"lemma": "animal, animālis, n.", "meaning": "animal"},
        {"lemma": "fera, ferae, f.", "meaning": "wild beast"},
        {"lemma": "avis, avis, f.", "meaning": "bird"},
        {"lemma": "piscis, piscis, m.", "meaning": "fish"},
        {"lemma": "canis, canis, m./f.", "meaning": "dog"},
        {"lemma": "equus, equī, m.", "meaning": "horse"},
        {"lemma": "bōs, bovis, m./f.", "meaning": "cow, ox"},
        {"lemma": "ovis, ovis, f.", "meaning": "sheep"},
        {"lemma": "porcus, porcī, m.", "meaning": "pig"}
    ],
    
    "Package 6: War, City & Society (Nouns III)": [
        {"lemma": "domus, domūs, f.", "meaning": "house, home"},
        {"lemma": "tēctum, tēctī, n.", "meaning": "roof, house"},
        {"lemma": "aedificium, aedificiī, n.", "meaning": "building"},
        {"lemma": "vīlla, vīllae, f.", "meaning": "country house, estate"},
        {"lemma": "oppidum, oppidī, n.", "meaning": "town"},
        {"lemma": "vīcus, vīcī, m.", "meaning": "village, neighborhood"},
        {"lemma": "via, viae, f.", "meaning": "street, road, way"},
        {"lemma": "iter, itineris, n.", "meaning": "journey, route, march"},
        {"lemma": "pōns, pontis, m.", "meaning": "bridge"},
        {"lemma": "porta, portae, f.", "meaning": "gate, door"},
        {"lemma": "iānua, iānuae, f.", "meaning": "door"},
        {"lemma": "fenestra, fenestrae, f.", "meaning": "window"},
        {"lemma": "mūrus, mūrī, m.", "meaning": "wall"},
        {"lemma": "moenia, moeniōrum, n. pl.", "meaning": "city walls"},
        {"lemma": "templum, templī, n.", "meaning": "temple"},
        {"lemma": "āra, ārae, f.", "meaning": "altar"},
        {"lemma": "forum, forī, n.", "meaning": "forum, marketplace"},
        {"lemma": "cūria, cūriae, f.", "meaning": "senate house"},
        {"lemma": "rēx, rēgis, m.", "meaning": "king"},
        {"lemma": "rēgīna, rēgīnae, f.", "meaning": "queen"},
        {"lemma": "prīnceps, principis, m.", "meaning": "leader, emperor, chief"},
        {"lemma": "cīvis, cīvis, m./f.", "meaning": "citizen"},
        {"lemma": "populus, populī, m.", "meaning": "people, nation"},
        {"lemma": "turba, turbae, f.", "meaning": "crowd, mob"},
        {"lemma": "gēns, gentis, f.", "meaning": "family, clan, nation"},
        {"lemma": "lēx, lēgis, f.", "meaning": "law"},
        {"lemma": "iūs, iūris, n.", "meaning": "right, justice, law"},
        {"lemma": "mōs, mōris, m.", "meaning": "custom, habit, tradition"},
        {"lemma": "pāx, pācis, f.", "meaning": "peace"},
        {"lemma": "bellum, bellī, n.", "meaning": "war"},
        {"lemma": "proelium, proeliī, n.", "meaning": "battle"},
        {"lemma": "pugna, pugnae, f.", "meaning": "fight, battle"},
        {"lemma": "mīles, mīlitis, m.", "meaning": "soldier"},
        {"lemma": "exercitus, exercitūs, m.", "meaning": "army"},
        {"lemma": "agmen, agminis, n.", "meaning": "column, marching army"},
        {"lemma": "castra, castrōrum, n. pl.", "meaning": "camp, military camp"},
        {"lemma": "arma, armōrum, n. pl.", "meaning": "arms, weapons"},
        {"lemma": "tēlum, tēlī, n.", "meaning": "weapon, spear"},
        {"lemma": "gladius, gladiī, m.", "meaning": "sword"},
        {"lemma": "ēnsis, ēnsis, m.", "meaning": "sword (poetic)"},
        {"lemma": "scūtum, scūtī, n.", "meaning": "shield"},
        {"lemma": "hasta, hastae, f.", "meaning": "spear"},
        {"lemma": "arcus, arcūs, m.", "meaning": "bow"},
        {"lemma": "sagitta, sagittae, f.", "meaning": "arrow"},
        {"lemma": "dux, ducis, m.", "meaning": "leader, general"},
        {"lemma": "hostis, hostis, m.", "meaning": "enemy"},
        {"lemma": "victor, victōris, m.", "meaning": "victor, conqueror"},
        {"lemma": "victōria, victōriae, f.", "meaning": "victory"},
        {"lemma": "classis, classis, f.", "meaning": "fleet"},
        {"lemma": "nāvis, nāvis, f.", "meaning": "ship, boat"}
    ],
    
    "Package 7: Size, Value & Quantity (Adjectives I)": [
        {"lemma": "parvus, -a, -um", "meaning": "small, little"},
        {"lemma": "brevis, breve", "meaning": "short, brief"},
        {"lemma": "altus, -a, -um", "meaning": "high, deep"},
        {"lemma": "lātus, -a, -um", "meaning": "wide, broad"},
        {"lemma": "gravis, grave", "meaning": "heavy, serious, severe"},
        {"lemma": "levis, leve", "meaning": "light, slight, trivial"},
        {"lemma": "ingēns, ingentis", "meaning": "huge, vast"},
        {"lemma": "clārus, -a, -um", "meaning": "clear, famous, bright"},
        {"lemma": "obscūrus, -a, -um", "meaning": "dark, obscure"},
        {"lemma": "plēnus, -a, -um", "meaning": "full"},
        {"lemma": "inānis, ināne", "meaning": "empty, vain"},
        {"lemma": "vacuus, -a, -um", "meaning": "empty, vacant"},
        {"lemma": "aequus, -a, -um", "meaning": "level, fair, equal, just"},
        {"lemma": "inīquus, -a, -um", "meaning": "uneven, unfair, unjust"},
        {"lemma": "certus, -a, -um", "meaning": "certain, sure, fixed"},
        {"lemma": "incertus, -a, -um", "meaning": "uncertain, unsure"},
        {"lemma": "vērus, -a, -um", "meaning": "true, real"},
        {"lemma": "falsus, -a, -um", "meaning": "false, fake"},
        {"lemma": "rēctus, -a, -um", "meaning": "straight, right"},
        {"lemma": "prāvus, -a, -um", "meaning": "crooked, wrong, depraved"},
        {"lemma": "dignus, -a, -um (+ abl.)", "meaning": "worthy, deserving"},
        {"lemma": "indignus, -a, -um", "meaning": "unworthy"},
        {"lemma": "cārus, -a, -um", "meaning": "dear, expensive"},
        {"lemma": "vīlis, vīle", "meaning": "cheap, worthless"},
        {"lemma": "dīves, dīvitis", "meaning": "rich, wealthy"},
        {"lemma": "pauper, pauperis", "meaning": "poor"},
        {"lemma": "fēlīx, fēlīcis", "meaning": "lucky, fortunate, happy"},
        {"lemma": "īnfēlīx, īnfēlīcis", "meaning": "unlucky, unfortunate"},
        {"lemma": "beātus, -a, -um", "meaning": "blessed, happy"},
        {"lemma": "miser, misera, miserum", "meaning": "wretched, miserable"},
        {"lemma": "fortis, forte", "meaning": "brave, strong"},
        {"lemma": "īnfirmus, -a, -um", "meaning": "weak, frail"},
        {"lemma": "validus, -a, -um", "meaning": "strong, valid"},
        {"lemma": "aeger, aegra, aegrum", "meaning": "sick, ill"},
        {"lemma": "sānus, -a, -um", "meaning": "healthy, sound"},
        {"lemma": "tūtus, -a, -um", "meaning": "safe"},
        {"lemma": "perīculōsus, -a, -um", "meaning": "dangerous"},
        {"lemma": "idōneus, -a, -um", "meaning": "suitable, fit"},
        {"lemma": "similis, simile (+ dat.)", "meaning": "similar, like"},
        {"lemma": "dissimilis, dissimile", "meaning": "unlike, different"},
        {"lemma": "quālis, quāle", "meaning": "what sort of, of what kind"},
        {"lemma": "tālis, tāle", "meaning": "such, of such a kind"},
        {"lemma": "quantus, -a, -um", "meaning": "how big, how much"},
        {"lemma": "tantus, -a, -um", "meaning": "so great, so much"},
        {"lemma": "tot (indeclinable)", "meaning": "so many"},
        {"lemma": "paucī, -ae, -a", "meaning": "few, a few"},
        {"lemma": "cēterī, -ae, -a", "meaning": "the rest, the others"},
        {"lemma": "reliquus, -a, -um", "meaning": "remaining, the rest of"},
        {"lemma": "plūres, plūra", "meaning": "more (plural)"},
        {"lemma": "ūllus, -a, -um", "meaning": "any"}
    ],
    
    "Package 8: Quality, Age & State (Adjectives II)": [
        {"lemma": "novus, -a, -um", "meaning": "new"},
        {"lemma": "antīquus, -a, -um", "meaning": "old, ancient"},
        {"lemma": "vetus, veteris", "meaning": "old"},
        {"lemma": "iuvenis, iuvenis", "meaning": "young"},
        {"lemma": "senex, senis", "meaning": "old, aged"},
        {"lemma": "recēns, recentis", "meaning": "recent, fresh"},
        {"lemma": "sacer, sacra, sacrum", "meaning": "sacred, holy"},
        {"lemma": "sānctus, -a, -um", "meaning": "holy, consecrated"},
        {"lemma": "profānus, -a, -um", "meaning": "secular, profane, unholy"},
        {"lemma": "pulcher, pulchra, pulchrum", "meaning": "beautiful, handsome"},
        {"lemma": "foedus, -a, -um", "meaning": "foul, ugly, filthy"},
        {"lemma": "turpis, turpe", "meaning": "ugly, shameful, base"},
        {"lemma": "fōrmōsus, -a, -um", "meaning": "beautiful, shapely"},
        {"lemma": "asper, aspera, asperum", "meaning": "rough, harsh"},
        {"lemma": "dulcis, dulce", "meaning": "sweet"},
        {"lemma": "amārus, -a, -um", "meaning": "bitter"},
        {"lemma": "dūrus, -a, -um", "meaning": "hard, harsh"},
        {"lemma": "mollis, molle", "meaning": "soft, gentle"},
        {"lemma": "calidus, -a, -um", "meaning": "hot, warm"},
        {"lemma": "frīgidus, -a, -um", "meaning": "cold"},
        {"lemma": "siccus, -a, -um", "meaning": "dry"},
        {"lemma": "ūmidus, -a, -um", "meaning": "wet, moist"},
        {"lemma": "albus, -a, -um", "meaning": "white (dull)"},
        {"lemma": "āter, ātra, ātrum", "meaning": "black, dark, deadly"},
        {"lemma": "niger, nigra, nigrum", "meaning": "black, glossy black"},
        {"lemma": "candidus, -a, -um", "meaning": "shining white, bright"},
        {"lemma": "ruber, rubra, rubrum", "meaning": "red"},
        {"lemma": "flāvus, -a, -um", "meaning": "yellow, blonde"},
        {"lemma": "viridis, viride", "meaning": "green"},
        {"lemma": "caeruleus, -a, -um", "meaning": "blue, sky-blue"},
        {"lemma": "aureus, -a, -um", "meaning": "golden"},
        {"lemma": "argenteus, -a, -um", "meaning": "silver, made of silver"},
        {"lemma": "ferreus, -a, -um", "meaning": "iron, made of iron"},
        {"lemma": "ligneus, -a, -um", "meaning": "wooden, made of wood"},
        {"lemma": "saxeus, -a, -um", "meaning": "rocky, made of stone"},
        {"lemma": "celer, celeris, celere", "meaning": "swift, quick"},
        {"lemma": "vēlōx, vēlōcis", "meaning": "fast, rapid"},
        {"lemma": "tardus, -a, -um", "meaning": "slow, late"},
        {"lemma": "lentus, -a, -um", "meaning": "slow, sluggish, sticky"},
        {"lemma": "sēgnis, sēgne", "meaning": "sluggish, lazy"},
        {"lemma": "laetus, -a, -um", "meaning": "happy, joyful"},
        {"lemma": "trīstis, trīste", "meaning": "sad, gloomy"},
        {"lemma": "īrātus, -a, -um", "meaning": "angry"},
        {"lemma": "placidus, -a, -um", "meaning": "calm, peaceful"},
        {"lemma": "ferōx, ferōcis", "meaning": "fierce, wild"},
        {"lemma": "saevus, -a, -um", "meaning": "savage, cruel"},
        {"lemma": "mītis, mīte", "meaning": "mild, gentle"},
        {"lemma": "crūdēlis, crūdēle", "meaning": "cruel"},
        {"lemma": "aliēnus, -a, -um", "meaning": "foreign, strange, someone else's"},
        {"lemma": "proprius, -a, -um", "meaning": "one's own, special, particular"}
    ],
    
    "Package 9: The Glue Part 1 (Adverbs)": [
        {"lemma": "haud", "meaning": "not at all, by no means"},
        {"lemma": "minimē", "meaning": "least, very little, no"},
        {"lemma": "ita", "meaning": "so, thus, in this way"},
        {"lemma": "sīc", "meaning": "thus, so, in such a way"},
        {"lemma": "tam", "meaning": "so, to such a degree"},
        {"lemma": "valdē", "meaning": "very, exceedingly"},
        {"lemma": "magis", "meaning": "more"},
        {"lemma": "maximē", "meaning": "most, especially"},
        {"lemma": "minus", "meaning": "less"},
        {"lemma": "paene", "meaning": "almost, nearly"},
        {"lemma": "ferē", "meaning": "almost, approximately"},
        {"lemma": "vix", "meaning": "scarcely, hardly"},
        {"lemma": "satis", "meaning": "enough, sufficiently"},
        {"lemma": "nimis", "meaning": "too much, excessively"},
        {"lemma": "multum", "meaning": "much, a lot"},
        {"lemma": "paulum", "meaning": "a little"},
        {"lemma": "iterum", "meaning": "again, a second time"},
        {"lemma": "rūrsus", "meaning": "back, again"},
        {"lemma": "saepe", "meaning": "often"},
        {"lemma": "numquam", "meaning": "never"},
        {"lemma": "semper", "meaning": "always"},
        {"lemma": "aliquandō", "meaning": "sometimes, at some time"},
        {"lemma": "quondam", "meaning": "once, formerly"},
        {"lemma": "ōlim", "meaning": "once upon a time, formerly"},
        {"lemma": "nūper", "meaning": "recently, lately"},
        {"lemma": "mox", "meaning": "soon"},
        {"lemma": "crās", "meaning": "tomorrow"},
        {"lemma": "hodiē", "meaning": "today"},
        {"lemma": "herī", "meaning": "yesterday"},
        {"lemma": "statim", "meaning": "immediately, at once"},
        {"lemma": "prōtinus", "meaning": "straightaway, immediately"},
        {"lemma": "tandem", "meaning": "finally, at last"},
        {"lemma": "deinde", "meaning": "then, next"},
        {"lemma": "deinceps", "meaning": "in turn, successively"},
        {"lemma": "posteā", "meaning": "afterward, later"},
        {"lemma": "praetereā", "meaning": "besides, moreover"},
        {"lemma": "anteā", "meaning": "before, previously"},
        {"lemma": "ubi", "meaning": "where, when"},
        {"lemma": "quō", "meaning": "where to, to what place"},
        {"lemma": "unde", "meaning": "from where, whence"},
        {"lemma": "quā", "meaning": "by which route, where"},
        {"lemma": "hīc", "meaning": "here, in this place"},
        {"lemma": "hūc", "meaning": "to here, hither"},
        {"lemma": "hinc", "meaning": "from here, hence"},
        {"lemma": "ibi", "meaning": "there, in that place"},
        {"lemma": "illīc", "meaning": "there, in that place (yonder)"},
        {"lemma": "bene", "meaning": "well"},
        {"lemma": "male", "meaning": "badly"},
        {"lemma": "subitō", "meaning": "suddenly"},
        {"lemma": "tamen", "meaning": "however, nevertheless"}
    ],
    
    "Package 10: The Glue Part 2 (Preps, Conjunctions & Questions)": [
        {"lemma": "prō (+ abl.)", "meaning": "for, on behalf of, in front of"},
        {"lemma": "prae (+ abl.)", "meaning": "before, in front of"},
        {"lemma": "sub (+ acc. / + abl.)", "meaning": "under, beneath"},
        {"lemma": "super (+ acc. / + abl.)", "meaning": "above, over"},
        {"lemma": "suprā (+ acc.)", "meaning": "above, beyond"},
        {"lemma": "trāns (+ acc.)", "meaning": "across, over"},
        {"lemma": "ob (+ acc.)", "meaning": "because of, on account of"},
        {"lemma": "propter (+ acc.)", "meaning": "because of, on account of"},
        {"lemma": "circum (+ acc.)", "meaning": "around"},
        {"lemma": "inter (+ acc.)", "meaning": "between, among"},
        {"lemma": "intrā (+ acc.)", "meaning": "within, inside"},
        {"lemma": "extrā (+ acc.)", "meaning": "outside, beyond"},
        {"lemma": "apud (+ acc.)", "meaning": "at the house of, near, among"},
        {"lemma": "autem", "meaning": "however, moreover"},
        {"lemma": "vērum", "meaning": "but, however, in truth"},
        {"lemma": "at", "meaning": "but, but yet"},
        {"lemma": "enim", "meaning": "for, indeed"},
        {"lemma": "nam", "meaning": "for"},
        {"lemma": "quia", "meaning": "because"},
        {"lemma": "quod", "meaning": "because, that"},
        {"lemma": "quoniam", "meaning": "since, inasmuch as"},
        {"lemma": "sī", "meaning": "if"},
        {"lemma": "nisi", "meaning": "unless, if not, except"},
        {"lemma": "etsī", "meaning": "even if, although"},
        {"lemma": "quamquam", "meaning": "although"},
        {"lemma": "quamvīs", "meaning": "however much, although"},
        {"lemma": "postquam", "meaning": "after"},
        {"lemma": "antequam", "meaning": "before"},
        {"lemma": "ut", "meaning": "so that, in order that, as"},
        {"lemma": "nē", "meaning": "lest, so that not"},
        {"lemma": "cūr", "meaning": "why"},
        {"lemma": "quandō", "meaning": "when"},
        {"lemma": "quōmodo", "meaning": "how"},
        {"lemma": "quis", "meaning": "who"},
        {"lemma": "quid", "meaning": "what"},
        {"lemma": "quot", "meaning": "how many"},
        {"lemma": "quantus, -a, -um", "meaning": "how big, how much"},
        {"lemma": "quālis, quāle", "meaning": "what sort of"},
        {"lemma": "uter, utra, utrum", "meaning": "which (of two)"},
        {"lemma": "neuter, neutra, neutrum", "meaning": "neither"},
        {"lemma": "alter, altera, alterum", "meaning": "the other (of two)"},
        {"lemma": "-ne (enclitic)", "meaning": "indicates a yes/no question"},
        {"lemma": "nōnne", "meaning": "surely (expects a yes answer)"},
        {"lemma": "num", "meaning": "surely not (expects a no answer)"},
        {"lemma": "aliquis, aliquid", "meaning": "someone, something"},
        {"lemma": "quīdam, quaedam, quoddam", "meaning": "a certain, some"},
        {"lemma": "quisque, quidque", "meaning": "each one, everyone"},
        {"lemma": "īdem, eadem, idem", "meaning": "the same"},
        {"lemma": "quīcumque, quaecumque, quodcumque", "meaning": "whoever, whatever"},
        {"lemma": "ipse, ipsa, ipsum", "meaning": "himself, herself, itself (intensive)"}
    ],
    "Package 11: Politics, State & Law": [
        {"lemma": "senātus, -ūs, m.", "meaning": "senate"},
        {"lemma": "cōnsul, -ulis, m.", "meaning": "consul"},
        {"lemma": "praetor, -ōris, m.", "meaning": "praetor, judge, official"},
        {"lemma": "magistrātus, -ūs, m.", "meaning": "magistrate, public office"},
        {"lemma": "imperātor, -ōris, m.", "meaning": "commander, general, emperor"},
        {"lemma": "rēs pūblica, reī pūblicae, f.", "meaning": "republic, state, public affairs"},
        {"lemma": "cōntiō, -ōnis, f.", "meaning": "public assembly, speech"},
        {"lemma": "comitia, -ōrum, n. pl.", "meaning": "elections, assembly"},
        {"lemma": "testis, -is, m./f.", "meaning": "witness"},
        {"lemma": "iūdex, iūdicis, m.", "meaning": "judge, juror"},
        {"lemma": "iūdicium, -ī, n.", "meaning": "judgment, trial, court"},
        {"lemma": "fās (indeclinable), n.", "meaning": "divine law, right"},
        {"lemma": "nefās (indeclinable), n.", "meaning": "sin, crime against the gods"},
        {"lemma": "scelus, sceleris, n.", "meaning": "crime, wickedness, sin"},
        {"lemma": "facinus, facinoris, n.", "meaning": "deed, crime, outrage"},
        {"lemma": "crīmen, crīminis, n.", "meaning": "charge, accusation, crime"},
        {"lemma": "poena, -ae, f.", "meaning": "punishment, penalty"},
        {"lemma": "supplicium, -ī, n.", "meaning": "punishment, torture, execution"},
        {"lemma": "cūstōdia, -ae, f.", "meaning": "protection, custody, guard"},
        {"lemma": "carcer, carceris, m.", "meaning": "prison, jail"},
        {"lemma": "catēna, -ae, f.", "meaning": "chain, fetter"},
        {"lemma": "fraus, fraudis, f.", "meaning": "deceit, fraud, trickery"},
        {"lemma": "dolus, -ī, m.", "meaning": "trick, deceit, cunning"},
        {"lemma": "fūrtum, -ī, n.", "meaning": "theft, robbery"},
        {"lemma": "īnsidiae, -ārum, f. pl.", "meaning": "ambush, plot, trap"},
        {"lemma": "prōditiō, -ōnis, f.", "meaning": "treason, betrayal"},
        {"lemma": "coniūrātiō, -ōnis, f.", "meaning": "conspiracy, plot"},
        {"lemma": "foedus, foederis, n.", "meaning": "treaty, agreement, pact"},
        {"lemma": "ōtium, -ī, n.", "meaning": "leisure, peace, free time"},
        {"lemma": "negōtium, -ī, n.", "meaning": "business, task, trouble"},
        {"lemma": "dīvitiae, -ārum, f. pl.", "meaning": "wealth, riches"},
        {"lemma": "paupertās, paupertātis, f.", "meaning": "poverty"},
        {"lemma": "inopia, -ae, f.", "meaning": "lack, scarcity, shortage"},
        {"lemma": "cōpia, -ae, f.", "meaning": "abundance, supply, (pl.) troops"},
        {"lemma": "praemium, -ī, n.", "meaning": "reward, prize"},
        {"lemma": "stīpendium, -ī, n.", "meaning": "pay, military service"},
        {"lemma": "sors, sortis, f.", "meaning": "lot, fate, destiny"},
        {"lemma": "grātia, -ae, f.", "meaning": "favor, influence, gratitude"},
        {"lemma": "invidia, -ae, f.", "meaning": "envy, jealousy, hatred"},
        {"lemma": "glōria, -ae, f.", "meaning": "glory, fame"},
        {"lemma": "fāma, -ae, f.", "meaning": "rumor, reputation, fame"},
        {"lemma": "rūmor, -ōris, m.", "meaning": "rumor, gossip"},
        {"lemma": "spēs, speī, f.", "meaning": "hope, expectation"},
        {"lemma": "cōnsēnsus, -ūs, m.", "meaning": "agreement, consensus"},
        {"lemma": "ōrātiō, -ōnis, f.", "meaning": "speech, oration"},
        {"lemma": "ōrātor, -ōris, m.", "meaning": "orator, speaker"},
        {"lemma": "cīvitās, cīvitātis, f.", "meaning": "citizenship, state, city"},
        {"lemma": "lēgātus, -ī, m.", "meaning": "envoy, ambassador, lieutenant"},
        {"lemma": "lēgātiō, -ōnis, f.", "meaning": "embassy, mission"},
        {"lemma": "pūblicānus, -ī, m.", "meaning": "tax collector"}
    ],
    
    "Package 12: Mind, Body & Abstract Nouns": [
        {"lemma": "mēns, mentis, f.", "meaning": "mind, thought, intention"},
        {"lemma": "ratiō, -ōnis, f.", "meaning": "reason, calculation, method"},
        {"lemma": "ingenium, -ī, n.", "meaning": "nature, talent, character"},
        {"lemma": "memoria, -ae, f.", "meaning": "memory, recollection"},
        {"lemma": "ars, artis, f.", "meaning": "art, skill, craft"},
        {"lemma": "scientia, -ae, f.", "meaning": "knowledge, science"},
        {"lemma": "disciplīna, -ae, f.", "meaning": "training, discipline, learning"},
        {"lemma": "prūdentia, -ae, f.", "meaning": "foresight, wisdom, prudence"},
        {"lemma": "sapientia, -ae, f.", "meaning": "wisdom, good sense"},
        {"lemma": "stultitia, -ae, f.", "meaning": "foolishness, stupidity"},
        {"lemma": "furor, -ōris, m.", "meaning": "madness, rage, fury"},
        {"lemma": "pavor, -ōris, m.", "meaning": "panic, sudden fear"},
        {"lemma": "terror, -ōris, m.", "meaning": "terror, dread"},
        {"lemma": "formīdō, -inis, f.", "meaning": "fear, terror, dread"},
        {"lemma": "metus, -ūs, m.", "meaning": "fear, anxiety"},
        {"lemma": "gaudium, -ī, n.", "meaning": "joy, gladness"},
        {"lemma": "laetitia, -ae, f.", "meaning": "happiness, joy"},
        {"lemma": "lūctus, -ūs, m.", "meaning": "grief, mourning, sorrow"},
        {"lemma": "gemitus, -ūs, m.", "meaning": "groan, sighing"},
        {"lemma": "lacrima, -ae, f.", "meaning": "tear"},
        {"lemma": "pudor, -ōris, m.", "meaning": "shame, modesty, decency"},
        {"lemma": "decus, decoris, n.", "meaning": "honor, glory, ornament"},
        {"lemma": "dēdecus, dēdecoris, n.", "meaning": "disgrace, dishonor"},
        {"lemma": "virtūs, virtūtis, f.", "meaning": "courage, virtue, excellence"},
        {"lemma": "vitium, -ī, n.", "meaning": "fault, vice, crime"},
        {"lemma": "pietās, pietātis, f.", "meaning": "duty, devotion, loyalty"},
        {"lemma": "fidēs, fideī, f.", "meaning": "faith, trust, loyalty"},
        {"lemma": "perfidia, -ae, f.", "meaning": "treachery, faithlessness"},
        {"lemma": "clēmentia, -ae, f.", "meaning": "mercy, clemency"},
        {"lemma": "sevēritās, sevēritātis, f.", "meaning": "strictness, severity"},
        {"lemma": "crūdēlitās, crūdēlitātis, f.", "meaning": "cruelty"},
        {"lemma": "audācia, -ae, f.", "meaning": "boldness, audacity"},
        {"lemma": "cōnstantia, -ae, f.", "meaning": "firmness, steadiness"},
        {"lemma": "fōrma, -ae, f.", "meaning": "shape, beauty, form"},
        {"lemma": "figūra, -ae, f.", "meaning": "shape, figure, form"},
        {"lemma": "pondus, ponderis, n.", "meaning": "weight, burden"},
        {"lemma": "numerus, -ī, m.", "meaning": "number"},
        {"lemma": "modus, -ī, m.", "meaning": "measure, limit, manner, way"},
        {"lemma": "ōrdō, ōrdinis, m.", "meaning": "order, rank, line"},
        {"lemma": "gradus, -ūs, m.", "meaning": "step, pace, rank"},
        {"lemma": "rōbur, rōboris, n.", "meaning": "oak, strength, wood"},
        {"lemma": "nervus, -ī, m.", "meaning": "sinew, muscle, string"},
        {"lemma": "vīrēs, vīrium, f. pl.", "meaning": "strength, forces"},
        {"lemma": "artus, -ūs, m.", "meaning": "joint, limb"},
        {"lemma": "latus, lateris, n.", "meaning": "side, flank"},
        {"lemma": "sinus, -ūs, m.", "meaning": "fold, curve, bosom, bay"},
        {"lemma": "gremium, -ī, n.", "meaning": "lap, bosom"},
        {"lemma": "cervīx, cervīcis, f.", "meaning": "neck"},
        {"lemma": "umerus, -ī, m.", "meaning": "shoulder"},
        {"lemma": "tellūs, tellūris, f.", "meaning": "earth, land"}
    ],
    
    "Package 13: Warfare, Weapons & Conflict": [
        {"lemma": "clipeus, -ī, m.", "meaning": "shield (round)"},
        {"lemma": "lōrīca, -ae, f.", "meaning": "breastplate, armor"},
        {"lemma": "galea, -ae, f.", "meaning": "helmet"},
        {"lemma": "pīlum, -ī, n.", "meaning": "javelin, heavy spear"},
        {"lemma": "iaculum, -ī, n.", "meaning": "dart, javelin"},
        {"lemma": "pugiō, pugiōnis, m.", "meaning": "dagger"},
        {"lemma": "aciēs, aciēī, f.", "meaning": "battle line, sharp edge"},
        {"lemma": "praesidium, -ī, n.", "meaning": "guard, garrison, protection"},
        {"lemma": "cornū, -ūs, n.", "meaning": "horn, wing of an army"},
        {"lemma": "subsidium, -ī, n.", "meaning": "help, relief, reserve troops"},
        {"lemma": "impedīmentum, -ī, n.", "meaning": "hindrance, (pl.) baggage"},
        {"lemma": "vāllum, -ī, n.", "meaning": "rampart, palisade"},
        {"lemma": "fossa, -ae, f.", "meaning": "ditch, trench"},
        {"lemma": "turris, turris, f.", "meaning": "tower"},
        {"lemma": "obsessiō, -ōnis, f.", "meaning": "siege, blockade"},
        {"lemma": "tumultus, -ūs, m.", "meaning": "uproar, confusion, riot"},
        {"lemma": "sēditiō, -ōnis, f.", "meaning": "rebellion, mutiny"},
        {"lemma": "sīca, -ae, f.", "meaning": "dagger, knife"},
        {"lemma": "spolia, -ōrum, n. pl.", "meaning": "spoils, booty, loot"},
        {"lemma": "praeda, -ae, f.", "meaning": "booty, plunder"},
        {"lemma": "triumphus, -ī, m.", "meaning": "triumph, victory parade"},
        {"lemma": "clādēs, clādis, f.", "meaning": "disaster, defeat, slaughter"},
        {"lemma": "exsilium, -ī, n.", "meaning": "exile, banishment"},
        {"lemma": "captīvus, -ī, m.", "meaning": "prisoner, captive"},
        {"lemma": "obses, obsidis, m./f.", "meaning": "hostage"},
        {"lemma": "eques, equitis, m.", "meaning": "horseman, knight, cavalry"},
        {"lemma": "pedes, peditis, m.", "meaning": "foot soldier, infantry"},
        {"lemma": "ratis, ratis, f.", "meaning": "raft, boat, ship"},
        {"lemma": "rēmus, -ī, m.", "meaning": "oar"},
        {"lemma": "vēlum, -ī, n.", "meaning": "sail"},
        {"lemma": "mōlēs, mōlis, f.", "meaning": "mass, huge structure, effort"},
        {"lemma": "onus, oneris, n.", "meaning": "burden, load, weight"},
        {"lemma": "signum, -ī, n.", "meaning": "sign, standard, signal"},
        {"lemma": "īctus, -ūs, m.", "meaning": "blow, strike, hit"},
        {"lemma": "impetus, -ūs, m.", "meaning": "attack, assault, charge"},
        {"lemma": "minae, -ārum, f. pl.", "meaning": "threats"},
        {"lemma": "rīpa, -ae, f.", "meaning": "river bank"},
        {"lemma": "lītus, lītoris, n.", "meaning": "shore, beach"},
        {"lemma": "fretum, -ī, n.", "meaning": "strait, channel, sea"},
        {"lemma": "vadum, -ī, n.", "meaning": "shallow, ford, shoal"},
        {"lemma": "portus, -ūs, m.", "meaning": "port, harbor"},
        {"lemma": "cohors, cohortis, f.", "meaning": "cohort, troop"},
        {"lemma": "manipulus, -ī, m.", "meaning": "maniple, handful"},
        {"lemma": "rēmex, rēmigis, m.", "meaning": "rower, oarsman"},
        {"lemma": "prōra, -ae, f.", "meaning": "prow, bow of a ship"},
        {"lemma": "carīna, -ae, f.", "meaning": "keel, ship"},
        {"lemma": "puppis, puppis, f.", "meaning": "stern, ship"},
        {"lemma": "gubernātor, -ōris, m.", "meaning": "pilot, helmsman, governor"},
        {"lemma": "nauta, -ae, m.", "meaning": "sailor"},
        {"lemma": "fīnis, fīnis, m.", "meaning": "end, boundary, limit"}
    ],
    
    "Package 14: Verbs of Violence & Action": [
        {"lemma": "vulnerō, -āre", "meaning": "to wound, injure"},
        {"lemma": "percutiō, percutere", "meaning": "to strike, pierce"},
        {"lemma": "caedō, caedere", "meaning": "to cut, cut down, kill"},
        {"lemma": "trucīdō, -āre", "meaning": "to slaughter, massacre"},
        {"lemma": "vāstō, -āre", "meaning": "to lay waste, destroy"},
        {"lemma": "spoliō, -āre", "meaning": "to rob, strip, plunder"},
        {"lemma": "dīripiō, dīripere", "meaning": "to tear apart, plunder"},
        {"lemma": "ēripiō, ēripere", "meaning": "to snatch away, rescue"},
        {"lemma": "cōnflīgō, cōnflīgere", "meaning": "to clash, fight"},
        {"lemma": "dīmicō, -āre", "meaning": "to fight, struggle"},
        {"lemma": "resistō, resistere (+ dat.)", "meaning": "to resist, pause"},
        {"lemma": "dēfendō, dēfendere", "meaning": "to defend, ward off"},
        {"lemma": "tueor, tuērī", "meaning": "to look at, protect, defend"},
        {"lemma": "prōtegō, prōtegere", "meaning": "to protect, cover"},
        {"lemma": "parcō, parcere (+ dat.)", "meaning": "to spare"},
        {"lemma": "servō, -āre", "meaning": "to save, keep, guard"},
        {"lemma": "cōnservō, -āre", "meaning": "to preserve, maintain"},
        {"lemma": "cūrō, -āre", "meaning": "to care for, cure"},
        {"lemma": "nūtriō, -īre", "meaning": "to nourish, feed"},
        {"lemma": "alō, alere", "meaning": "to feed, nourish, support"},
        {"lemma": "foveō, fovēre", "meaning": "to warm, cherish"},
        {"lemma": "excitō, -āre", "meaning": "to wake, rouse, excite"},
        {"lemma": "sollicitō, -āre", "meaning": "to disturb, stir up"},
        {"lemma": "turbō, -āre", "meaning": "to throw into confusion, disturb"},
        {"lemma": "plācō, -āre", "meaning": "to appease, calm"},
        {"lemma": "dēmōnstrō, -āre", "meaning": "to point out, show"},
        {"lemma": "ostendō, ostendere", "meaning": "to show, display"},
        {"lemma": "patefaciō, patefacere", "meaning": "to lay open, reveal"},
        {"lemma": "lateō, latēre", "meaning": "to lie hidden, hide"},
        {"lemma": "cēlō, -āre", "meaning": "to hide, conceal"},
        {"lemma": "occulō, occulere", "meaning": "to cover up, hide"},
        {"lemma": "dēcipiō, dēcipere", "meaning": "to deceive, catch"},
        {"lemma": "fallō, fallere", "meaning": "to deceive, slip by"},
        {"lemma": "circumveniō, circumvenīre", "meaning": "to surround, cheat"},
        {"lemma": "opprimō, opprimere", "meaning": "to crush, overwhelm"},
        {"lemma": "urgeō, urgēre", "meaning": "to press, urge, push"},
        {"lemma": "pendeō, pendēre", "meaning": "to hang, depend"},
        {"lemma": "pendō, pendere", "meaning": "to weigh, pay"},
        {"lemma": "sternō, sternere", "meaning": "to spread, scatter, strike down"},
        {"lemma": "spargō, spargere", "meaning": "to scatter, sprinkle"},
        {"lemma": "serō, serere", "meaning": "to sow, plant"},
        {"lemma": "carpō, carpere", "meaning": "to pluck, seize"},
        {"lemma": "secō, secāre", "meaning": "to cut, slice"},
        {"lemma": "dīvidō, dīvidere", "meaning": "to divide, separate"},
        {"lemma": "misceō, miscēre", "meaning": "to mix, mingle"},
        {"lemma": "iungō, iungere", "meaning": "to join, unite"},
        {"lemma": "fīgō, fīgere", "meaning": "to fix, fasten, pierce"},
        {"lemma": "sūmō, sūmere", "meaning": "to take, take up"},
        {"lemma": "dēligō, dēligere", "meaning": "to choose, select"},
        {"lemma": "exigō, exigere", "meaning": "to drive out, exact, demand"}
    ],
    
    "Package 15: Essential Verbs (Movement & State)": [
        {"lemma": "surgō, surgere", "meaning": "to rise, stand up"},
        {"lemma": "cōnsīdō, cōnsīdere", "meaning": "to sit down, settle"},
        {"lemma": "iaceō, iacēre", "meaning": "to lie down, lie dead"},
        {"lemma": "rēpō, rēpere", "meaning": "to crawl, creep"},
        {"lemma": "saliō, salīre", "meaning": "to leap, jump"},
        {"lemma": "lābor, lābī", "meaning": "to slip, slide, glide"},
        {"lemma": "ruō, ruere", "meaning": "to rush, fall, ruin"},
        {"lemma": "prōcēdō, prōcēdere", "meaning": "to go forward, advance"},
        {"lemma": "recēdō, recēdere", "meaning": "to go back, withdraw"},
        {"lemma": "discēdō, discēdere", "meaning": "to depart, leave"},
        {"lemma": "accēdō, accēdere", "meaning": "to approach, go to"},
        {"lemma": "subeō, subīre", "meaning": "to go under, undergo"},
        {"lemma": "trānseō, trānsīre", "meaning": "to cross over, go across"},
        {"lemma": "redeō, redīre", "meaning": "to return, go back"},
        {"lemma": "obeō, obīre", "meaning": "to go to meet, die"},
        {"lemma": "pereō, perīre", "meaning": "to perish, die"},
        {"lemma": "intereō, interīre", "meaning": "to die, perish"},
        {"lemma": "vehō, vehere", "meaning": "to convey, carry, ride"},
        {"lemma": "pelliciō, pellicere", "meaning": "to entice, lure"},
        {"lemma": "cōgō, cōgere", "meaning": "to force, compel, gather"},
        {"lemma": "agō, agere", "meaning": "to do, drive, act"},
        {"lemma": "cōnor, cōnārī", "meaning": "to try, attempt"},
        {"lemma": "experior, experīrī", "meaning": "to test, experience, try"},
        {"lemma": "audeō, audēre", "meaning": "to dare, be bold"},
        {"lemma": "cessō, -āre", "meaning": "to delay, cease, hesitate"},
        {"lemma": "moror, morārī", "meaning": "to delay, linger"},
        {"lemma": "festīnō, -āre", "meaning": "to hurry, hasten"},
        {"lemma": "vītō, -āre", "meaning": "to avoid, shun"},
        {"lemma": "lūdō, lūdere", "meaning": "to play, mock"},
        {"lemma": "salūtō, -āre", "meaning": "to greet, salute"},
        {"lemma": "vīsitō, -āre", "meaning": "to visit, see often"},
        {"lemma": "habitō, -āre", "meaning": "to live in, dwell"},
        {"lemma": "cēnō, -āre", "meaning": "to dine, eat dinner"},
        {"lemma": "bibō, bibere", "meaning": "to drink"},
        {"lemma": "edō, edere", "meaning": "to eat"},
        {"lemma": "dēvorō, -āre", "meaning": "to devour, swallow"},
        {"lemma": "hauriō, haurīre", "meaning": "to drain, drink up, swallow"},
        {"lemma": "spīrō, -āre", "meaning": "to breathe"},
        {"lemma": "stertō, -ēre", "meaning": "to snore"},
        {"lemma": "vigilō, -āre", "meaning": "to stay awake, watch"},
        {"lemma": "dormiō, -īre", "meaning": "to sleep"},
        {"lemma": "quiēscō, quiēscere", "meaning": "to rest, be quiet"},
        {"lemma": "sūdō, -āre", "meaning": "to sweat, perspire"},
        {"lemma": "palpō, -āre", "meaning": "to stroke, touch gently"},
        {"lemma": "tremō, tremere", "meaning": "to tremble, shake"},
        {"lemma": "micō, micāre", "meaning": "to twinkle, flash, tremble"},
        {"lemma": "fulgeō, fulgēre", "meaning": "to shine, flash, gleam"},
        {"lemma": "lūceō, lūcēre", "meaning": "to shine, be bright"},
        {"lemma": "ārdēo, ārdēre", "meaning": "to burn, be on fire"},
        {"lemma": "flagrō, -āre", "meaning": "to blaze, burn"}
    ],
    
    "Package 16: Essential Verbs (Mental & Social)": [
        {"lemma": "cēnseō, cēnsēre", "meaning": "to assess, vote, think"},
        {"lemma": "reor, rērī", "meaning": "to think, believe"},
        {"lemma": "suspicor, suspicārī", "meaning": "to suspect"},
        {"lemma": "aestimō, -āre", "meaning": "to value, estimate"},
        {"lemma": "probō, -āre", "meaning": "to approve, prove"},
        {"lemma": "improbō, -āre", "meaning": "to disapprove, condemn"},
        {"lemma": "damnō, -āre", "meaning": "to condemn, sentence"},
        {"lemma": "pūniō, -īre", "meaning": "to punish"},
        {"lemma": "vindicō, -āre", "meaning": "to avenge, claim"},
        {"lemma": "iūrō, -āre", "meaning": "to swear, take an oath"},
        {"lemma": "voveō, vovēre", "meaning": "to vow, promise"},
        {"lemma": "dēdō, dēdere", "meaning": "to surrender, hand over"},
        {"lemma": "trādō, trādere", "meaning": "to hand over, surrender, relate"},
        {"lemma": "reddō, reddere", "meaning": "to return, give back"},
        {"lemma": "ēdō, ēdere", "meaning": "to put forth, publish"},
        {"lemma": "addō, addere", "meaning": "to add"},
        {"lemma": "condō, condere", "meaning": "to found, establish, hide"},
        {"lemma": "circumdō, circumdare", "meaning": "to surround, put around"},
        {"lemma": "mandō, -āre", "meaning": "to order, command, entrust"},
        {"lemma": "commendō, -āre", "meaning": "to entrust, recommend"},
        {"lemma": "flāgitō, -āre", "meaning": "to demand, urgently ask"},
        {"lemma": "recūsō, -āre", "meaning": "to refuse, object"},
        {"lemma": "negō, -āre", "meaning": "to deny, say no"},
        {"lemma": "inquam, inquis, inquit", "meaning": "to say (used in quotes)"},
        {"lemma": "for, fārī", "meaning": "to speak, say"},
        {"lemma": "dīsserō, dīsserere", "meaning": "to discuss, argue"},
        {"lemma": "colloquor, colloquī", "meaning": "to converse, talk"},
        {"lemma": "fateor, fatērī", "meaning": "to confess, admit"},
        {"lemma": "cōnfiteor, cōnfitērī", "meaning": "to confess, acknowledge"},
        {"lemma": "sileō, silēre", "meaning": "to be silent, be still"},
        {"lemma": "taceō, tacēre", "meaning": "to be silent, keep quiet"},
        {"lemma": "nītor, nītī", "meaning": "to struggle, lean on"},
        {"lemma": "queror, querī", "meaning": "to complain, lament"},
        {"lemma": "ūtor, ūtī (+ abl.)", "meaning": "to use"},
        {"lemma": "fruor, fruī (+ abl.)", "meaning": "to enjoy"},
        {"lemma": "fungor, fungī (+ abl.)", "meaning": "to perform, discharge"},
        {"lemma": "potior, potīrī (+ abl.)", "meaning": "to get possession of"},
        {"lemma": "vescor, vescī (+ abl.)", "meaning": "to feed on, eat"},
        {"lemma": "nāscor, nāscī", "meaning": "to be born"},
        {"lemma": "orior, orīrī", "meaning": "to rise, arise, begin"},
        {"lemma": "morior, morī", "meaning": "to die"},
        {"lemma": "pariō, parere", "meaning": "to give birth to, produce"},
        {"lemma": "gignō, gignere", "meaning": "to beget, bear, produce"},
        {"lemma": "creō, -āre", "meaning": "to create, elect"},
        {"lemma": "ēducō, -āre", "meaning": "to bring up, educate"},
        {"lemma": "valeō, valēre", "meaning": "to be strong, be well"},
        {"lemma": "pateō, patēre", "meaning": "to be open, be visible"},
        {"lemma": "egeō, egēre (+ abl.)", "meaning": "to lack, need"},
        {"lemma": "careō, carēre (+ abl.)", "meaning": "to lack, be without"},
        {"lemma": "abundō, -āre", "meaning": "to overflow, abound"}
    ],
    
    "Package 17: Adjectives (Morality & Measurement)": [
        {"lemma": "castus, -a, -um", "meaning": "pure, chaste"},
        {"lemma": "pius, -a, -um", "meaning": "devoted, dutiful, pious"},
        {"lemma": "impius, -a, -um", "meaning": "wicked, disloyal, impious"},
        {"lemma": "scelestus, -a, -um", "meaning": "wicked, criminal"},
        {"lemma": "dīvīnus, -a, -um", "meaning": "divine"},
        {"lemma": "hūmānus, -a, -um", "meaning": "human, humane"},
        {"lemma": "ferus, -a, -um", "meaning": "wild, savage"},
        {"lemma": "immānis, immāne", "meaning": "huge, monstrous"},
        {"lemma": "dīrus, -a, -um", "meaning": "awful, dire, dreadful"},
        {"lemma": "cavus, -a, -um", "meaning": "hollow"},
        {"lemma": "caecus, -a, -um", "meaning": "blind, blind, hidden"},
        {"lemma": "mūtus, -a, -um", "meaning": "mute, silent"},
        {"lemma": "surdus, -a, -um", "meaning": "deaf"},
        {"lemma": "claudus, -a, -um", "meaning": "lame, limping"},
        {"lemma": "vīvus, -a, -um", "meaning": "alive, living"},
        {"lemma": "mortuus, -a, -um", "meaning": "dead"},
        {"lemma": "inermis, inerme", "meaning": "unarmed"},
        {"lemma": "armātus, -a, -um", "meaning": "armed"},
        {"lemma": "nūdus, -a, -um", "meaning": "naked, bare"},
        {"lemma": "tacitus, -a, -um", "meaning": "silent, quiet"},
        {"lemma": "sēcrētus, -a, -um", "meaning": "secret, hidden"},
        {"lemma": "crēber, crēbra, crēbrum", "meaning": "frequent, crowded"},
        {"lemma": "rārus, -a, -um", "meaning": "rare, scattered"},
        {"lemma": "dēnsus, -a, -um", "meaning": "thick, dense"},
        {"lemma": "tenuis, tenue", "meaning": "thin, slight, fine"},
        {"lemma": "crassus, -a, -um", "meaning": "thick, fat, coarse"},
        {"lemma": "laevus, -a, -um", "meaning": "left, ill-omened"},
        {"lemma": "dexter, dextra, dextrum", "meaning": "right, favorable"},
        {"lemma": "sinister, sinistra, sinistrum", "meaning": "left, evil"},
        {"lemma": "pūblicus, -a, -um", "meaning": "public, of the state"},
        {"lemma": "prīvātus, -a, -um", "meaning": "private, personal"},
        {"lemma": "familiāris, familiāre", "meaning": "belonging to the family, friendly"},
        {"lemma": "nōbilis, nōbile", "meaning": "noble, famous"},
        {"lemma": "ignōbilis, ignōbile", "meaning": "unknown, common, ignoble"},
        {"lemma": "subitus, -a, -um", "meaning": "sudden"},
        {"lemma": "pinguis, pingue", "meaning": "fat, rich, fertile"},
        {"lemma": "macer, macra, macrum", "meaning": "lean, skinny"},
        {"lemma": "illūstris, illūstre", "meaning": "bright, famous, brilliant"},
        {"lemma": "ignōtus, -a, -um", "meaning": "unknown"},
        {"lemma": "plēbēius, -a, -um", "meaning": "plebeian, common"},
        {"lemma": "rēgius, -a, -um", "meaning": "royal, kingly"},
        {"lemma": "atrōx, atrōcis", "meaning": "fierce, savage, bloody"},
        {"lemma": "fīdus, -a, -um", "meaning": "faithful, loyal"},
        {"lemma": "īnfīdus, -a, -um", "meaning": "unfaithful, treacherous"},
        {"lemma": "iūstus, -a, -um", "meaning": "just, fair, rightful"},
        {"lemma": "integer, integra, integrum", "meaning": "whole, untouched, honest"},
        {"lemma": "saucius, -a, -um", "meaning": "wounded"},
        {"lemma": "mātūrus, -a, -um", "meaning": "ripe, mature, early"},
        {"lemma": "crūdus, -a, -um", "meaning": "raw, bloody, cruel"},
        {"lemma": "memor, memoris (+ gen.)", "meaning": "mindful, remembering"}
    ],
    
    "Package 18: Nouns (Religion, Lit & Senses)": [
        {"lemma": "āctiō, -ōnis, f.", "meaning": "action, deed, lawsuit"},
        {"lemma": "vōtum, -ī, n.", "meaning": "vow, prayer"},
        {"lemma": "nūmen, nūminis, n.", "meaning": "divine power, divinity"},
        {"lemma": "fātum, -ī, n.", "meaning": "fate, destiny, doom"},
        {"lemma": "rītus, -ūs, m.", "meaning": "rite, ceremony, custom"},
        {"lemma": "sacerdōs, sacerdōtis, m./f.", "meaning": "priest, priestess"},
        {"lemma": "precēs, precum, f. pl.", "meaning": "prayers, entreaties"},
        {"lemma": "vātēs, vātis, m./f.", "meaning": "prophet, bard, poet"},
        {"lemma": "ōrāculum, -ī, n.", "meaning": "oracle"},
        {"lemma": "lūcus, -ī, m.", "meaning": "sacred grove"},
        {"lemma": "mōnstrum, -ī, n.", "meaning": "monster, omen, warning"},
        {"lemma": "prōdigium, -ī, n.", "meaning": "omen, portent, prodigy"},
        {"lemma": "ōmen, ōminis, n.", "meaning": "sign, omen"},
        {"lemma": "venēnum, -ī, n.", "meaning": "poison, drug"},
        {"lemma": "pōculum, -ī, n.", "meaning": "cup, drinking bowl"},
        {"lemma": "patera, -ae, f.", "meaning": "shallow bowl (for libations)"},
        {"lemma": "daps, dapis, f.", "meaning": "feast, banquet"},
        {"lemma": "epulae, -ārum, f. pl.", "meaning": "banquet, feast"},
        {"lemma": "famēs, famis, f.", "meaning": "hunger, famine"},
        {"lemma": "sitis, sitis, f.", "meaning": "thirst"},
        {"lemma": "cibus, -ī, m.", "meaning": "food"},
        {"lemma": "pānis, pānī, m.", "meaning": "bread"},
        {"lemma": "vīnum, -ī, n.", "meaning": "wine"},
        {"lemma": "merum, -ī, n.", "meaning": "pure wine, unmixed wine"},
        {"lemma": "mel, mellis, n.", "meaning": "honey"},
        {"lemma": "sāl, salis, m.", "meaning": "salt, wit"},
        {"lemma": "oleum, -ī, n.", "meaning": "oil, olive oil"},
        {"lemma": "liber, librī, m.", "meaning": "book"},
        {"lemma": "epistula, -ae, f.", "meaning": "letter"},
        {"lemma": "littera, -ae, f.", "meaning": "letter (alphabet), literature"},
        {"lemma": "fābula, -ae, f.", "meaning": "story, play, fable"},
        {"lemma": "carmen, carminis, n.", "meaning": "song, poem, spell"},
        {"lemma": "poēta, -ae, m.", "meaning": "poet"},
        {"lemma": "versus, -ūs, m.", "meaning": "verse, line of poetry"},
        {"lemma": "iocus, -ī, m.", "meaning": "joke, jest"},
        {"lemma": "rīsus, -ūs, m.", "meaning": "laughter, smile"},
        {"lemma": "sūdor, sūdōris, m.", "meaning": "sweat"},
        {"lemma": "tenebrae, -ārum, f. pl.", "meaning": "darkness, shadows"},
        {"lemma": "fūmus, -ī, m.", "meaning": "smoke"},
        {"lemma": "cinis, cineris, m.", "meaning": "ash, ruins"},
        {"lemma": "favīlla, -ae, f.", "meaning": "glowing ash, spark"},
        {"lemma": "lūmen, lūminis, n.", "meaning": "light, eye"},
        {"lemma": "iubar, iubaris, n.", "meaning": "radiance, beam of light"},
        {"lemma": "color, colōris, m.", "meaning": "color"},
        {"lemma": "sonus, -ī, m.", "meaning": "sound, noise"},
        {"lemma": "strepitus, -ūs, m.", "meaning": "noise, uproar, crash"},
        {"lemma": "murmur, murmuris, n.", "meaning": "murmur, rumble, roar"},
        {"lemma": "silentium, -ī, n.", "meaning": "silence"},
        {"lemma": "odor, odōris, m.", "meaning": "smell, scent, odor"},
        {"lemma": "sapor, sapōris, m.", "meaning": "taste, flavor"}
    ],
    
    "Package 19: Form & Matter (Nature & Arch.)": [
        {"lemma": "aurum, -ī, n.", "meaning": "gold"},
        {"lemma": "argentum, -ī, n.", "meaning": "silver"},
        {"lemma": "ferrum, -ī, n.", "meaning": "iron, sword"},
        {"lemma": "aes, aeris, n.", "meaning": "bronze, copper, money"},
        {"lemma": "plumbum, -ī, n.", "meaning": "lead"},
        {"lemma": "marmor, marmoris, n.", "meaning": "marble"},
        {"lemma": "lignum, -ī, n.", "meaning": "wood, timber"},
        {"lemma": "tignum, -ī, n.", "meaning": "log, beam"},
        {"lemma": "trabs, trabis, f.", "meaning": "beam, timber, ship"},
        {"lemma": "rāmus, -ī, m.", "meaning": "branch, bough"},
        {"lemma": "frōns, frondis, f.", "meaning": "leaf, foliage"},
        {"lemma": "frūx, frūgis, f.", "meaning": "fruit, crop"},
        {"lemma": "sēmen, sēminis, n.", "meaning": "seed"},
        {"lemma": "seges, segetis, f.", "meaning": "crop, cornfield"},
        {"lemma": "rādīx, rādīcis, f.", "meaning": "root"},
        {"lemma": "vītis, vītis, f.", "meaning": "vine, grapevine"},
        {"lemma": "ūva, -ae, f.", "meaning": "grape, bunch of grapes"},
        {"lemma": "rēte, rētis, n.", "meaning": "net"},
        {"lemma": "cassis, cassis, m.", "meaning": "hunting net"},
        {"lemma": "laqueus, -ī, m.", "meaning": "noose, snare"},
        {"lemma": "nōdus, -ī, m.", "meaning": "knot"},
        {"lemma": "fūnis, fūnis, m.", "meaning": "rope, cable"},
        {"lemma": "restis, restis, f.", "meaning": "rope, cord"},
        {"lemma": "clāvus, -ī, m.", "meaning": "nail, spike, rudder"},
        {"lemma": "rota, -ae, f.", "meaning": "wheel"},
        {"lemma": "currus, -ūs, m.", "meaning": "chariot"},
        {"lemma": "essedum, -ī, n.", "meaning": "war chariot"},
        {"lemma": "iugum, -ī, n.", "meaning": "yoke, mountain ridge"},
        {"lemma": "frēnum, -ī, n.", "meaning": "rein, bridle"},
        {"lemma": "habēna, -ae, f.", "meaning": "strap, rein"},
        {"lemma": "calcar, calcāris, n.", "meaning": "spur"},
        {"lemma": "lōrum, -ī, n.", "meaning": "thong, rein, whip"},
        {"lemma": "flagellum, -ī, n.", "meaning": "whip, scourge"},
        {"lemma": "verbera, -um, n. pl.", "meaning": "lashes, blows, whipping"},
        {"lemma": "fāstīgium, -ī, n.", "meaning": "summit, roof, slope"},
        {"lemma": "culmen, culminis, n.", "meaning": "top, summit, roof"},
        {"lemma": "līmen, līminis, n.", "meaning": "threshold, doorway"},
        {"lemma": "postis, postis, m.", "meaning": "doorpost"},
        {"lemma": "cardō, cardinis, m.", "meaning": "hinge, pivot, crisis"},
        {"lemma": "clāvis, clāvis, f.", "meaning": "key"},
        {"lemma": "claustrum, -ī, n.", "meaning": "bolt, bar, barrier"},
        {"lemma": "fornīx, fornīcis, m.", "meaning": "arch, vault"},
        {"lemma": "scalae, -ārum, f. pl.", "meaning": "stairs, ladder"},
        {"lemma": "aedēs, aedis, f.", "meaning": "temple, (pl.) house"},
        {"lemma": "ātrium, -ī, n.", "meaning": "atrium, main hall"},
        {"lemma": "thalamus, -ī, m.", "meaning": "bedroom, bridal chamber"},
        {"lemma": "torus, -ī, m.", "meaning": "bed, couch, cushion"},
        {"lemma": "cubīle, cubīlis, n.", "meaning": "bed, resting place"},
        {"lemma": "sēdēs, sēdis, f.", "meaning": "seat, abode, home"},
        {"lemma": "solum, -ī, n.", "meaning": "ground, soil, floor"}
    ],
    
    "Package 20: The Glue Part 3 (Fine Details)": [
        {"lemma": "circiter", "meaning": "around, about, near"},
        {"lemma": "contrā (+ acc.)", "meaning": "against, opposite"},
        {"lemma": "ergā (+ acc.)", "meaning": "towards (of feelings)"},
        {"lemma": "praeter (+ acc.)", "meaning": "beyond, except, past"},
        {"lemma": "iūxtā (+ acc.)", "meaning": "next to, near, beside"},
        {"lemma": "clam", "meaning": "secretly, in secret"},
        {"lemma": "cōram (+ abl.)", "meaning": "face to face, in the presence of"},
        {"lemma": "palam", "meaning": "openly, publicly"},
        {"lemma": "tenus (+ abl. / gen.)", "meaning": "as far as, up to"},
        {"lemma": "prōrsus", "meaning": "forward, absolutely, entirely"},
        {"lemma": "funditus", "meaning": "from the bottom, utterly"},
        {"lemma": "omnīnō", "meaning": "altogether, completely"},
        {"lemma": "paulātim", "meaning": "little by little, gradually"},
        {"lemma": "sēnsim", "meaning": "gradually, slowly"},
        {"lemma": "certē", "meaning": "certainly, surely"},
        {"lemma": "profectō", "meaning": "actually, really, truly"},
        {"lemma": "quidem", "meaning": "indeed, in fact"},
        {"lemma": "equidem", "meaning": "truly, for my part"},
        {"lemma": "vidēlicet", "meaning": "clearly, namely, of course"},
        {"lemma": "scīlicet", "meaning": "of course, obviously"},
        {"lemma": "nimīrum", "meaning": "without a doubt, certainly"},
        {"lemma": "nēquāquam", "meaning": "by no means, not at all"},
        {"lemma": "quīn", "meaning": "why not, but that"},
        {"lemma": "quōminus", "meaning": "so that not, from"},
        {"lemma": "quārē", "meaning": "for what reason, therefore"},
        {"lemma": "quāpropter", "meaning": "why, wherefore"},
        {"lemma": "idcircō", "meaning": "for that reason, therefore"},
        {"lemma": "ideō", "meaning": "therefore, for that reason"},
        {"lemma": "adeō", "meaning": "so much, to such a degree"},
        {"lemma": "sīn", "meaning": "but if"},
        {"lemma": "dōnec", "meaning": "until, as long as"},
        {"lemma": "quoad", "meaning": "as long as, until"},
        {"lemma": "seu / sīve", "meaning": "or if, whether...or"},
        {"lemma": "nī", "meaning": "unless, if not"},
        {"lemma": "ceu", "meaning": "as, like, as if"},
        {"lemma": "velut", "meaning": "just as, like"},
        {"lemma": "tamquam", "meaning": "as if, just as"},
        {"lemma": "quasi", "meaning": "as if, nearly"},
        {"lemma": "utinam", "meaning": "if only, would that"},
        {"lemma": "sānē", "meaning": "truly, to be sure"},
        {"lemma": "forte", "meaning": "by chance, perhaps"},
        {"lemma": "forsitan", "meaning": "perhaps"},
        {"lemma": "nempe", "meaning": "truly, obviously"},
        {"lemma": "ultrō", "meaning": "voluntarily, beyond"},
        {"lemma": "sponte", "meaning": "voluntarily, of one's own accord"},
        {"lemma": "frūstrā", "meaning": "in vain"},
        {"lemma": "nēquīquam", "meaning": "to no purpose, in vain"},
        {"lemma": "temere", "meaning": "rashly, blindly, blindly"},
        {"lemma": "dēmum", "meaning": "at last, finally"},
        {"lemma": "videlicet", "meaning": "one may see, evidently"}
    ]
}
