# vocab_db.py

vocab_db = {
    "Package 1 (Top 1-20)": [
        {"lemma": "sum, esse, fuī, futūrus", "meaning": "to be, exist"},
        {"lemma": "et", "meaning": "and, even, also"},
        {"lemma": "quī, quae, quod", "meaning": "who, which, what, that"},
        {"lemma": "que (enclitic)", "meaning": "and"},
        {"lemma": "in (+ acc. / + abl.)", "meaning": "in, into, against"},
        {"lemma": "is, ea, id", "meaning": "he, she, it, this, that"},
        {"lemma": "nōn", "meaning": "not"},
        {"lemma": "hic, haec, hoc", "meaning": "this, these"},
        {"lemma": "ille, illa, illud", "meaning": "that, those"},
        {"lemma": "tū, tuī, tibi, tē", "meaning": "you"},
        {"lemma": "cum (conjunction / prep.)", "meaning": "with, when, since, although"},
        {"lemma": "ego, meī, mihi, mē", "meaning": "I, me"},
        {"lemma": "quisquam, quicquam", "meaning": "anyone, anything"},
        {"lemma": "ad (+ acc.)", "meaning": "to, towards, at"},
        {"lemma": "multus, -a, -um", "meaning": "much, many"},
        {"lemma": "omnis, omne", "meaning": "all, every"},
        {"lemma": "suī, sibi, sē", "meaning": "himself, herself, itself, themselves"},
        {"lemma": "nec / neque", "meaning": "and not, nor"},
        {"lemma": "sed", "meaning": "but"},
        {"lemma": "ā / ab (+ abl.)", "meaning": "from, by, away from"}
    ],
    "Package 2 (Top 21-40)": [
        {"lemma": "ipse, ipsa, ipsum", "meaning": "himself, herself, itself"},
        {"lemma": "deus, deī, m.", "meaning": "god"},
        {"lemma": "meus, -a, -um", "meaning": "my, mine"},
        {"lemma": "suus, -a, -um", "meaning": "his, her, its, their"},
        {"lemma": "dō, dāre, dedī, datus", "meaning": "to give"},
        {"lemma": "rēs, reī, f.", "meaning": "thing, matter, affair, business"},
        {"lemma": "iam", "meaning": "now, already"},
        {"lemma": "magnus, -a, -um", "meaning": "great, large, big"},
        {"lemma": "alius, alia, aliud", "meaning": "other, another"},
        {"lemma": "habeō, habēre, habuī, habitus", "meaning": "to have, hold"},
        {"lemma": "animus, animī, m.", "meaning": "mind, spirit, soul"},
        {"lemma": "noster, nostra, nostrum", "meaning": "our, ours"},
        {"lemma": "possum, posse, potuī", "meaning": "to be able, can"},
        {"lemma": "nihil / nīl", "meaning": "nothing"},
        {"lemma": "videō, vidēre, vīdī, vīsus", "meaning": "to see"},
        {"lemma": "bonus, -a, -um", "meaning": "good"},
        {"lemma": "tempus, temporis, n.", "meaning": "time"},
        {"lemma": "locus, locī, m.", "meaning": "place, location"},
        {"lemma": "homō, hominis, m.", "meaning": "human, man, person"},
        {"lemma": "dīcō, dīcere, dīxī, dictus", "meaning": "to say, speak, tell"}
    ],
    "Package 3 (Top 41-60)": [
        {"lemma": "faciō, facere, fēcī, factus", "meaning": "to make, do"},
        {"lemma": "tuus, -a, -um", "meaning": "your, yours"},
        {"lemma": "nullus, -a, -um", "meaning": "no, none"},
        {"lemma": "urbs, urbis, f.", "meaning": "city"},
        {"lemma": "diēs, diēī, m./f.", "meaning": "day"},
        {"lemma": "manus, manūs, f.", "meaning": "hand, band of men"},
        {"lemma": "pater, patris, m.", "meaning": "father"},
        {"lemma": "causa, causae, f.", "meaning": "cause, reason, case"},
        {"lemma": "volō, velle, voluī", "meaning": "to want, wish"},
        {"lemma": "per (+ acc.)", "meaning": "through, by means of"},
        {"lemma": "domus, domūs, f.", "meaning": "house, home"},
        {"lemma": "medius, -a, -um", "meaning": "middle, middle of"},
        {"lemma": "ferō, ferre, tulī, lātus", "meaning": "to bear, carry, bring, endure"},
        {"lemma": "amor, amōris, m.", "meaning": "love"},
        {"lemma": "vir, virī, m.", "meaning": "man, husband, hero"},
        {"lemma": "relinquō, relinquere, relīquī, relictus", "meaning": "to leave behind, abandon"},
        {"lemma": "corpus, corporis, n.", "meaning": "body"},
        {"lemma": "vīta, vītae, f.", "meaning": "life"},
        {"lemma": "sine (+ abl.)", "meaning": "without"},
        {"lemma": "eō, īre, iī / īvī, itus", "meaning": "to go"}
    ],
    "Package 4 (Top 61-80)": [
        {"lemma": "oculus, oculī, m.", "meaning": "eye"},
        {"lemma": "teneō, tenēre, tenuī, tentus", "meaning": "to hold, keep"},
        {"lemma": "mare, maris, n.", "meaning": "sea"},
        {"lemma": "caput, capitis, n.", "meaning": "head"},
        {"lemma": "regnum, regnī, n.", "meaning": "kingdom, royal power"},
        {"lemma": "pars, partis, f.", "meaning": "part, direction"},
        {"lemma": "nōmen, nōminis, n.", "meaning": "name"},
        {"lemma": "māter, mātris, f.", "meaning": "mother"},
        {"lemma": "audiō, audīre, audīvī, audītus", "meaning": "to hear, listen"},
        {"lemma": "gravis, grave", "meaning": "heavy, serious, severe"},
        {"lemma": "nox, noctis, f.", "meaning": "night"},
        {"lemma": "vincō, vincere, vīcī, victus", "meaning": "to conquer, defeat"},
        {"lemma": "mittō, mittere, mīsī, missus", "meaning": "to send, let go"},
        {"lemma": "mīles, mīlitis, m.", "meaning": "soldier"},
        {"lemma": "fidēs, fideī, f.", "meaning": "faith, trust, loyalty"},
        {"lemma": "vīs, vīs, f.", "meaning": "force, power, strength"},
        {"lemma": "malus, -a, -um", "meaning": "bad, evil"},
        {"lemma": "ager, agrī, m.", "meaning": "field, land"},
        {"lemma": "sciō, scīre, scīvī, scītus", "meaning": "to know"},
        {"lemma": "vōx, vōcis, f.", "meaning": "voice, word"}
    ],
    "Package 5 (Top 81-100)": [
        {"lemma": "caelum, caelī, n.", "meaning": "sky, heaven"},
        {"lemma": "pōnō, pōnere, posuī, positus", "meaning": "to put, place"},
        {"lemma": "arma, armōrum, n. pl.", "meaning": "arms, weapons"},
        {"lemma": "ōs, ōris, n.", "meaning": "mouth, face"},
        {"lemma": "annus, annī, m.", "meaning": "year"},
        {"lemma": "labor, labōris, m.", "meaning": "work, labor, effort"},
        {"lemma": "mōns, montis, m.", "meaning": "mountain"},
        {"lemma": "via, viae, f.", "meaning": "road, way, path"},
        {"lemma": "verbum, verbī, n.", "meaning": "word"},
        {"lemma": "crēdō, crēdere, crēdidī, crēditus", "meaning": "to believe, trust"},
        {"lemma": "petō, petere, petīvī, petītus", "meaning": "to seek, attack, aim at"},
        {"lemma": "mēns, mentis, f.", "meaning": "mind, thought, intention"},
        {"lemma": "ignis, ignis, m.", "meaning": "fire"},
        {"lemma": "novus, -a, -um", "meaning": "new, strange"},
        {"lemma": "genus, generis, n.", "meaning": "origin, kind, type, family"},
        {"lemma": "longus, -a, -um", "meaning": "long"},
        {"lemma": "parēns, parentis, m./f.", "meaning": "parent"},
        {"lemma": "puer, puerī, m.", "meaning": "boy"},
        {"lemma": "fuga, fugae, f.", "meaning": "flight, escape"},
        {"lemma": "cūra, curae, f.", "meaning": "care, anxiety, concern"}
    ]
}

# You can keep copying and pasting new packages here!
# Just follow the exact syntax:
# "Package Name": [ {"lemma": "latin word", "meaning": "translation"}, ... ],
