vocab_db = {
    "Package 1: The Absolute Core (Top 50)": [
        {"lemma": "sum, esse, fuī, futūrus", "meaning": "to be, exist"},
        {"lemma": "et", "meaning": "and"},
        {"lemma": "in (+ acc. / + abl.)", "meaning": "in, into, on, against"},
        {"lemma": "que (enclitic)", "meaning": "and"},
        {"lemma": "quī, quae, quod", "meaning": "who, which, what, that"},
        {"lemma": "nōn", "meaning": "not"},
        {"lemma": "hic, haec, hoc", "meaning": "this, these"},
        {"lemma": "ille, illa, illud", "meaning": "that, those"},
        {"lemma": "tū, tuī, tibi, tē", "meaning": "you"},
        {"lemma": "cum", "meaning": "with, when, since, although"},
        {"lemma": "ego, meī, mihi, mē", "meaning": "I, me"},
        {"lemma": "ad (+ acc.)", "meaning": "to, toward, at"},
        {"lemma": "suus, -a, -um", "meaning": "his, her, its, their (own)"},
        {"lemma": "is, ea, id", "meaning": "he, she, it, this, that"},
        {"lemma": "nec / neque", "meaning": "and not, nor"},
        {"lemma": "sed", "meaning": "but"},
        {"lemma": "omnis, omne", "meaning": "all, every"},
        {"lemma": "ā / ab (+ abl.)", "meaning": "from, away from, by"},
        {"lemma": "deus, deī, m.", "meaning": "god"},
        {"lemma": "rēs, reī, f.", "meaning": "thing, matter, business"},
        {"lemma": "iam", "meaning": "now, already"},
        {"lemma": "dō, dare, dedī, datus", "meaning": "to give"},
        {"lemma": "atque / ac", "meaning": "and, and also"},
        {"lemma": "alius, alia, aliud", "meaning": "other, another"},
        {"lemma": "multus, -a, -um", "meaning": "much, many"},
        {"lemma": "magnus, -a, -um", "meaning": "great, big, large"},
        {"lemma": "ē / ex (+ abl.)", "meaning": "out of, from"},
        {"lemma": "suī, sibi, sē", "meaning": "himself, herself, itself, themselves"},
        {"lemma": "habeō, habēre, habuī, habitus", "meaning": "to have, hold"},
        {"lemma": "animus, animī, m.", "meaning": "mind, spirit, soul"},
        {"lemma": "noster, nostra, nostrum", "meaning": "our, ours"},
        {"lemma": "possum, posse, potuī", "meaning": "to be able, can"},
        {"lemma": "nihil / nīl", "meaning": "nothing"},
        {"lemma": "videō, vidēre, vīdī, vīsus", "meaning": "to see"},
        {"lemma": "dē (+ abl.)", "meaning": "about, concerning, down from"},
        {"lemma": "per (+ acc.)", "meaning": "through, along, by means of"},
        {"lemma": "faciō, facere, fēcī, factus", "meaning": "to make, do"},
        {"lemma": "tuus, -a, -um", "meaning": "your, yours"},
        {"lemma": "locus, locī, m.", "meaning": "place, location"},
        {"lemma": "bonus, -a, -um", "meaning": "good"},
        {"lemma": "tempus, temporis, n.", "meaning": "time"},
        {"lemma": "dīcō, dīcere, dīxī, dictus", "meaning": "to say, speak, tell"},
        {"lemma": "nullus, -a, -um", "meaning": "no, none"},
        {"lemma": "homō, hominis, m.", "meaning": "human, man, person"},
        {"lemma": "urbs, urbis, f.", "meaning": "city"},
        {"lemma": "diēs, diēī, m./f.", "meaning": "day"},
        {"lemma": "manus, manūs, f.", "meaning": "hand, band of men"},
        {"lemma": "pater, patris, m.", "meaning": "father"},
        {"lemma": "causa, causae, f.", "meaning": "cause, reason"},
        {"lemma": "volō, velle, voluī", "meaning": "to want, wish"}
    ],
    
    "Package 2: Action & Motion (Verbs I)": [
        {"lemma": "veniō, venīre, vēnī, ventus", "meaning": "to come"},
        {"lemma": "eō, īre, iī, itus", "meaning": "to go"},
        {"lemma": "ferō, ferre, tulī, lātus", "meaning": "to bear, carry, bring"},
        {"lemma": "mittō, mittere, mīsī, missus", "meaning": "to send"},
        {"lemma": "relinquō, relinquere, relīquī, relictus", "meaning": "to leave behind, abandon"},
        {"lemma": "pōnō, pōnere, posuī, positus", "meaning": "to put, place"},
        {"lemma": "petō, petere, petīvī, petītus", "meaning": "to seek, attack, head for"},
        {"lemma": "fugiō, fugere, fūgī, fugitus", "meaning": "to flee, run away"},
        {"lemma": "currō, currere, cucurrī, cursus", "meaning": "to run"},
        {"lemma": "cadō, cadere, cecidī, cāsus", "meaning": "to fall"},
        {"lemma": "iaciō, iacere, iēcī, iactus", "meaning": "to throw"},
        {"lemma": "capiō, capere, cēpī, captus", "meaning": "to take, capture"},
        {"lemma": "rapiō, rapere, rapuī, raptus", "meaning": "to snatch, seize"},
        {"lemma": "dūcō, dūcere, dūxī, ductus", "meaning": "to lead"},
        {"lemma": "trahō, trahere, trāxī, tractus", "meaning": "to drag, draw"},
        {"lemma": "pellō, pellere, pepulī, pulsus", "meaning": "to drive, push"},
        {"lemma": "vincō, vincere, vīcī, victus", "meaning": "to conquer, win"},
        {"lemma": "stō, stāre, stetī, status", "meaning": "to stand"},
        {"lemma": "ambulō, ambulāre, ambulāvī, ambulātus", "meaning": "to walk"},
        {"lemma": "properō, properāre, properāvī", "meaning": "to hurry, hasten"},
        {"lemma": "maneō, manēre, mānsī, mānsus", "meaning": "to remain, stay"},
        {"lemma": "ascendō, ascendere, ascendī", "meaning": "to climb, ascend"},
        {"lemma": "dēscendō, dēscendere, dēscendī", "meaning": "to climb down, descend"},
        {"lemma": "errō, errāre, errāvī, errātus", "meaning": "to wander, make a mistake"},
        {"lemma": "moveō, movēre, mōvī, mōtus", "meaning": "to move"},
        {"lemma": "vīvō, vīvere, vīxī, vīctus", "meaning": "to live"},
        {"lemma": "necō, necāre, necāvī, necātus", "meaning": "to kill"},
        {"lemma": "interficiō, interficere, interfēcī", "meaning": "to kill, destroy"},
        {"lemma": "pugnō, pugnāre, pugnāvī, pugnātus", "meaning": "to fight"},
        {"lemma": "oppugnō, oppugnāre, oppugnāvī", "meaning": "to attack"},
        {"lemma": "aedificō, aedificāre, aedificāvī", "meaning": "to build"},
        {"lemma": "nāvigō, nāvigāre, nāvigāvī", "meaning": "to sail"},
        {"lemma": "portō, portāre, portāvī, portātus", "meaning": "to carry"},
        {"lemma": "iubeō, iubēre, iussī, iussus", "meaning": "to order, command"},
        {"lemma": "pāreō, pārēre, pāruī (+ dat.)", "meaning": "to obey"},
        {"lemma": "cēdō, cēdere, cessī, cessus", "meaning": "to yield, give way, go"},
        {"lemma": "quaerō, quaerere, quaesīvī, quaesītus", "meaning": "to search for, ask, seek"},
        {"lemma": "inveniō, invenīre, invēnī, inventus", "meaning": "to find, discover"},
        {"lemma": "perdō, perdere, perdidī, perditus", "meaning": "to destroy, lose"},
        {"lemma": "teneō, tenēre, tenuī, tentus", "meaning": "to hold, keep"},
        {"lemma": "retineō, retinēre, retinuī", "meaning": "to hold back, retain"},
        {"lemma": "claudō, claudere, clausī, clausus", "meaning": "to close, shut"},
        {"lemma": "aperiō, aperīre, aperuī, apertus", "meaning": "to open"},
        {"lemma": "tegō, tegere, tēxī, tēctus", "meaning": "to cover, hide"},
        {"lemma": "frangō, frangere, frēgī, frāctus", "meaning": "to break"},
        {"lemma": "rumpō, rumpere, rūpī, ruptus", "meaning": "to burst, break"},
        {"lemma": "vertō, vertere, vertī, versus", "meaning": "to turn"},
        {"lemma": "volvō, volvere, volvī, volūtus", "meaning": "to roll, turn over"},
        {"lemma": "premō, premere, pressī, pressus", "meaning": "to press, crush"},
        {"lemma": "tangō, tangere, tetigī, tāctus", "meaning": "to touch"}
    ],
    
    "Package 3: Mind, Senses & Speech (Verbs II)": [
        {"lemma": "audiō, audīre, audīvī, audītus", "meaning": "to hear, listen"},
        {"lemma": "sentiō, sentīre, sēnsī, sēnsus", "meaning": "to feel, perceive"},
        {"lemma": "sciō, scīre, scīvī, scītus", "meaning": "to know"},
        {"lemma": "nesciō, nescīre, nescīvī", "meaning": "to not know"},
        {"lemma": "putō, putāre, putāvī, putātus", "meaning": "to think"},
        {"lemma": "crēdō, crēdere, crēdidī (+ dat.)", "meaning": "to believe, trust"},
        {"lemma": "spērō, spērāre, spērāvī", "meaning": "to hope"},
        {"lemma": "timeō, timēre, timuī", "meaning": "to fear, be afraid"},
        {"lemma": "terreō, terrēre, terruī, territus", "meaning": "to frighten, terrify"},
        {"lemma": "gaudeō, gaudēre, gavīsus sum", "meaning": "to rejoice, be glad"},
        {"lemma": "rīdeō, rīdēre, rīsī, rīsus", "meaning": "to laugh, smile"},
        {"lemma": "fleō, flēre, flēvī, flētus", "meaning": "to weep, cry"},
        {"lemma": "doleō, dolēre, doluī", "meaning": "to suffer, grieve, hurt"},
        {"lemma": "mīror, mīrārī, mīrātus sum", "meaning": "to wonder at, admire"},
        {"lemma": "soleō, solēre, solitus sum", "meaning": "to be accustomed to, usually"},
        {"lemma": "cupiō, cupere, cupīvī, cupītus", "meaning": "to desire, want"},
        {"lemma": "amō, amāre, amāvī, amātus", "meaning": "to love, like"},
        {"lemma": "placeō, placēre, placuī (+ dat.)", "meaning": "to please"},
        {"lemma": "licet, licēre, licuit", "meaning": "it is permitted, allowed"},
        {"lemma": "decet, decēre, decuit", "meaning": "it is fitting, proper"},
        {"lemma": "oportet, oportēre, oportuit", "meaning": "it is necessary, one ought"},
        {"lemma": "rogō, rogāre, rogāvī, rogātus", "meaning": "to ask"},
        {"lemma": "ōrō, ōrāre, ōrāvī, ōrātus", "meaning": "to pray, beg, plead"},
        {"lemma": "vocō, vocāre, vocāvī, vocātus", "meaning": "to call"},
        {"lemma": "clāmō, clamāre, clāmāvī", "meaning": "to shout"},
        {"lemma": "respondeō, respondēre, respondī", "meaning": "to answer, reply"},
        {"lemma": "nūntiō, nūntiāre, nūntiāvī", "meaning": "to announce, report"},
        {"lemma": "mōnstrō, monstrāre, monstrāvī", "meaning": "to show, point out"},
        {"lemma": "doceō, docēre, docuī, doctus", "meaning": "to teach"},
        {"lemma": "discō, discere, didicī", "meaning": "to learn"},
        {"lemma": "legō, legere, lēgī, lēctus", "meaning": "to read, choose, gather"},
        {"lemma": "scrībō, scrībere, scrīpsī, scrīptus", "meaning": "to write"},
        {"lemma": "canō, canere, cecinī, cantus", "meaning": "to sing"},
        {"lemma": "cantō, cantāre, cantāvī", "meaning": "to sing, chant"},
        {"lemma": "moneō, monēre, monuī, monitus", "meaning": "to warn, advise"},
        {"lemma": "cōnsulō, cōnsulere, cōnsuluī", "meaning": "to consult, consider"},
        {"lemma": "statuō, statuere, statuī", "meaning": "to decide, set up"},
        {"lemma": "cōnstituō, cōnstituere, cōnstituī", "meaning": "to decide, establish"},
        {"lemma": "iūdicō, iūdicāre, iūdicāvī", "meaning": "to judge, decide"},
        {"lemma": "arbitror, arbitrārī, arbitrātus sum", "meaning": "to judge, think"},
        {"lemma": "cōgitō, cōgitāre, cōgitāvī", "meaning": "to think, consider"},
        {"lemma": "meminī, meminisse", "meaning": "to remember"},
        {"lemma": "oblīvīscor, oblīvīscī, oblītus sum", "meaning": "to forget"},
        {"lemma": "īgnōscō, ignōscere, ignōvī (+ dat.)", "meaning": "to forgive, pardon"},
        {"lemma": "imperō, imperāre, imperāvī (+ dat.)", "meaning": "to command, order"},
        {"lemma": "vetō, vetāre, vetuī, vetitus", "meaning": "to forbid"},
        {"lemma": "suādeō, suādēre, suāsī (+ dat.)", "meaning": "to urge, recommend"},
        {"lemma": "persuādeō, persuādēre, persuāsī", "meaning": "to persuade"},
        {"lemma": "postulō, postulāre, postulāvī", "meaning": "to demand"},
        {"lemma": "hortor, hortārī, hortātus sum", "meaning": "to urge, encourage"}
    ],
    
    "Package 4: People, Family & The Body (Nouns I)": [
        {"lemma": "māter, mātris, f.", "meaning": "mother"},
        {"lemma": "frāter, frātris, m.", "meaning": "brother"},
        {"lemma": "soror, sorōris, f.", "meaning": "sister"},
        {"lemma": "fīlius, fīliī, m.", "meaning": "son"},
        {"lemma": "fīlia, fīliae, f.", "meaning": "daughter"},
        {"lemma": "puer, puerī, m.", "meaning": "boy"},
        {"lemma": "puella, puellae, f.", "meaning": "girl"},
        {"lemma": "vir, virī, m.", "meaning": "man, husband"},
        {"lemma": "fēmina, fēminae, f.", "meaning": "woman"},
        {"lemma": "uxor, uxōris, f.", "meaning": "wife"},
        {"lemma": "marītus, maritī, m.", "meaning": "husband"},
        {"lemma": "īnfāns, īnfantis, m./f.", "meaning": "infant, baby"},
        {"lemma": "iuvenis, iuvenis, m.", "meaning": "young man, youth"},
        {"lemma": "senex, senis, m.", "meaning": "old man"},
        {"lemma": "avus, avī, m.", "meaning": "grandfather"},
        {"lemma": "dominus, dominī, m.", "meaning": "master, lord"},
        {"lemma": "domina, dominae, f.", "meaning": "mistress, lady"},
        {"lemma": "servus, servī, m.", "meaning": "slave"},
        {"lemma": "ancilla, ancillae, f.", "meaning": "slave-girl"},
        {"lemma": "amīcus, amīcī, m.", "meaning": "friend"},
        {"lemma": "amīca, amīcae, f.", "meaning": "female friend, girlfriend"},
        {"lemma": "comes, comitis, m./f.", "meaning": "companion, comrade"},
        {"lemma": "socius, sociī, m.", "meaning": "ally, comrade"},
        {"lemma": "hospes, hospitis, m./f.", "meaning": "guest, host, stranger"},
        {"lemma": "magister, magistrī, m.", "meaning": "teacher, master"},
        {"lemma": "discipulus, discipulī, m.", "meaning": "student, pupil"},
        {"lemma": "caput, capitis, n.", "meaning": "head"},
        {"lemma": "oculus, oculī, m.", "meaning": "eye"},
        {"lemma": "ōs, ōris, n.", "meaning": "mouth, face"},
        {"lemma": "auris, auris, f.", "meaning": "ear"},
        {"lemma": "dēns, dentis, m.", "meaning": "tooth"},
        {"lemma": "vultus, vultūs, m.", "meaning": "face, expression"},
        {"lemma": "frōns, frontis, f.", "meaning": "forehead, front"},
        {"lemma": "pectus, pectoris, n.", "meaning": "chest, breast, heart"},
        {"lemma": "cor, cordis, n.", "meaning": "heart"},
        {"lemma": "tergum, tergī, n.", "meaning": "back, rear"},
        {"lemma": "venter, ventris, m.", "meaning": "stomach, belly"},
        {"lemma": "bracchium, bracchiī, n.", "meaning": "arm"},
        {"lemma": "pēs, pedis, m.", "meaning": "foot"},
        {"lemma": "digitus, digitī, m.", "meaning": "finger, toe"},
        {"lemma": "crūs, crūris, n.", "meaning": "leg"},
        {"lemma": "sanguis, sanguinis, m.", "meaning": "blood"},
        {"lemma": "os, ossis, n.", "meaning": "bone"},
        {"lemma": "cutis, cutis, f.", "meaning": "skin"},
        {"lemma": "vulnus, vulneris, n.", "meaning": "wound"},
        {"lemma": "morbus, morbī, m.", "meaning": "disease, illness"},
        {"lemma": "vīta, vītae, f.", "meaning": "life"},
        {"lemma": "salūs, salūtis, f.", "meaning": "health, safety, greeting"},
        {"lemma": "lētum, lētī, n.", "meaning": "death, ruin"},
        {"lemma": "fūnus, fūneris, n.", "meaning": "funeral, death"}
    ],
    
    "Package 5: Nature, Space & Time (Nouns II)": [
        {"lemma": "terra, terrae, f.", "meaning": "earth, land, ground"},
        {"lemma": "caelum, caelī, n.", "meaning": "sky, heaven"},
        {"lemma": "sōl, sōlis, m.", "meaning": "sun"},
        {"lemma": "lūna, lūnae, f.", "meaning": "moon"},
        {"lemma": "stēlla, stēllae, f.", "meaning": "star"},
        {"lemma": "astrum, astrī, n.", "meaning": "star, constellation"},
        {"lemma": "mare, maris, n.", "meaning": "sea"},
        {"lemma": "aqua, aquae, f.", "meaning": "water"},
        {"lemma": "flūmen, flūminis, n.", "meaning": "river"},
        {"lemma": "amnis, amnis, m.", "meaning": "river, stream"},
        {"lemma": "unda, undae, f.", "meaning": "wave, water"},
        {"lemma": "fōns, fontis, m.", "meaning": "spring, fountain"},
        {"lemma": "ignis, ignis, m.", "meaning": "fire"},
        {"lemma": "flamma, flammae, f.", "meaning": "flame"},
        {"lemma": "ventus, ventī, m.", "meaning": "wind"},
        {"lemma": "aura, aurae, f.", "meaning": "breeze, air"},
        {"lemma": "tempestās, tempestātis, f.", "meaning": "storm, weather"},
        {"lemma": "nūbēs, nūbis, f.", "meaning": "cloud"},
        {"lemma": "imber, imbris, m.", "meaning": "rain, rainstorm"},
        {"lemma": "nix, nivis, f.", "meaning": "snow"},
        {"lemma": "hiems, hiemis, f.", "meaning": "winter"},
        {"lemma": "aestās, aestātis, f.", "meaning": "summer"},
        {"lemma": "vēr, vēris, n.", "meaning": "spring (season)"},
        {"lemma": "autumnus, autumnī, m.", "meaning": "autumn, fall"},
        {"lemma": "annus, annī, m.", "meaning": "year"},
        {"lemma": "mēnsis, mēnsis, m.", "meaning": "month"},
        {"lemma": "nox, noctis, f.", "meaning": "night"},
        {"lemma": "hōra, hōrae, f.", "meaning": "hour"},
        {"lemma": "mōns, montis, m.", "meaning": "mountain"},
        {"lemma": "collis, collis, m.", "meaning": "hill"},
        {"lemma": "vallis, vallis, f.", "meaning": "valley"},
        {"lemma": "campus, campī, m.", "meaning": "plain, field"},
        {"lemma": "silva, silvae, f.", "meaning": "forest, woods"},
        {"lemma": "nemus, nemoris, n.", "meaning": "grove, wood"},
        {"lemma": "arbor, arboris, f.", "meaning": "tree"},
        {"lemma": "flōs, flōris, m.", "meaning": "flower"},
        {"lemma": "herba, herbae, f.", "meaning": "grass, plant"},
        {"lemma": "saxum, saxī, n.", "meaning": "rock, stone"},
        {"lemma": "lapis, lapidis, m.", "meaning": "stone"},
        {"lemma": "harēna, harenae, f.", "meaning": "sand"},
        {"lemma": "pulvis, pulveris, m.", "meaning": "dust"},
        {"lemma": "animal, animālis, n.", "meaning": "animal"},
        {"lemma": "fera, ferae, f.", "meaning": "wild beast"},
        {"lemma": "avis, avis, f.", "meaning": "bird"},
        {"lemma": "piscis, piscis, m.", "meaning": "fish"},
        {"lemma": "canis, canis, m./f.", "meaning": "dog"},
        {"lemma": "equus, equī, m.", "meaning": "horse"},
        {"lemma": "bōs, bovis, m./f.", "meaning": "cow, ox"},
        {"lemma": "ovis, ovis, f.", "meaning": "sheep"},
        {"lemma": "porcus, porcī, m.", "meaning": "pig"}
    ],
    
    "Package 6: War, City & Society (Nouns III)": [
        {"lemma": "domus, domūs, f.", "meaning": "house, home"},
        {"lemma": "tēctum, tēctī, n.", "meaning": "roof, house"},
        {"lemma": "aedificium, aedificiī, n.", "meaning": "building"},
        {"lemma": "vīlla, vīllae, f.", "meaning": "country house, estate"},
        {"lemma": "oppidum, oppidī, n.", "meaning": "town"},
        {"lemma": "vīcus, vīcī, m.", "meaning": "village, neighborhood"},
        {"lemma": "via, viae, f.", "meaning": "street, road, way"},
        {"lemma": "iter, itineris, n.", "meaning": "journey, route, march"},
        {"lemma": "pōns, pontis, m.", "meaning": "bridge"},
        {"lemma": "porta, portae, f.", "meaning": "gate, door"},
        {"lemma": "iānua, iānuae, f.", "meaning": "door"},
        {"lemma": "fenestra, fenestrae, f.", "meaning": "window"},
        {"lemma": "mūrus, mūrī, m.", "meaning": "wall"},
        {"lemma": "moenia, moeniōrum, n. pl.", "meaning": "city walls"},
        {"lemma": "templum, templī, n.", "meaning": "temple"},
        {"lemma": "āra, ārae, f.", "meaning": "altar"},
        {"lemma": "forum, forī, n.", "meaning": "forum, marketplace"},
        {"lemma": "cūria, cūriae, f.", "meaning": "senate house"},
        {"lemma": "rēx, rēgis, m.", "meaning": "king"},
        {"lemma": "rēgīna, rēgīnae, f.", "meaning": "queen"},
        {"lemma": "prīnceps, principis, m.", "meaning": "leader, emperor, chief"},
        {"lemma": "cīvis, cīvis, m./f.", "meaning": "citizen"},
        {"lemma": "populus, populī, m.", "meaning": "people, nation"},
        {"lemma": "turba, turbae, f.", "meaning": "crowd, mob"},
        {"lemma": "gēns, gentis, f.", "meaning": "family, clan, nation"},
        {"lemma": "lēx, lēgis, f.", "meaning": "law"},
        {"lemma": "iūs, iūris, n.", "meaning": "right, justice, law"},
        {"lemma": "mōs, mōris, m.", "meaning": "custom, habit, tradition"},
        {"lemma": "pāx, pācis, f.", "meaning": "peace"},
        {"lemma": "bellum, bellī, n.", "meaning": "war"},
        {"lemma": "proelium, proeliī, n.", "meaning": "battle"},
        {"lemma": "pugna, pugnae, f.", "meaning": "fight, battle"},
        {"lemma": "mīles, mīlitis, m.", "meaning": "soldier"},
        {"lemma": "exercitus, exercitūs, m.", "meaning": "army"},
        {"lemma": "agmen, agminis, n.", "meaning": "column, marching army"},
        {"lemma": "castra, castrōrum, n. pl.", "meaning": "camp, military camp"},
        {"lemma": "arma, armōrum, n. pl.", "meaning": "arms, weapons"},
        {"lemma": "tēlum, tēlī, n.", "meaning": "weapon, spear"},
        {"lemma": "gladius, gladiī, m.", "meaning": "sword"},
        {"lemma": "ēnsis, ēnsis, m.", "meaning": "sword (poetic)"},
        {"lemma": "scūtum, scūtī, n.", "meaning": "shield"},
        {"lemma": "hasta, hastae, f.", "meaning": "spear"},
        {"lemma": "arcus, arcūs, m.", "meaning": "bow"},
        {"lemma": "sagitta, sagittae, f.", "meaning": "arrow"},
        {"lemma": "dux, ducis, m.", "meaning": "leader, general"},
        {"lemma": "hostis, hostis, m.", "meaning": "enemy"},
        {"lemma": "victor, victōris, m.", "meaning": "victor, conqueror"},
        {"lemma": "victōria, victōriae, f.", "meaning": "victory"},
        {"lemma": "classis, classis, f.", "meaning": "fleet"},
        {"lemma": "nāvis, nāvis, f.", "meaning": "ship, boat"}
    ],
    
    "Package 7: Size, Value & Quantity (Adjectives I)": [
        {"lemma": "parvus, -a, -um", "meaning": "small, little"},
        {"lemma": "brevis, breve", "meaning": "short, brief"},
        {"lemma": "altus, -a, -um", "meaning": "high, deep"},
        {"lemma": "lātus, -a, -um", "meaning": "wide, broad"},
        {"lemma": "gravis, grave", "meaning": "heavy, serious, severe"},
        {"lemma": "levis, leve", "meaning": "light, slight, trivial"},
        {"lemma": "ingēns, ingentis", "meaning": "huge, vast"},
        {"lemma": "clārus, -a, -um", "meaning": "clear, famous, bright"},
        {"lemma": "obscūrus, -a, -um", "meaning": "dark, obscure"},
        {"lemma": "plēnus, -a, -um", "meaning": "full"},
        {"lemma": "inānis, ināne", "meaning": "empty, vain"},
        {"lemma": "vacuus, -a, -um", "meaning": "empty, vacant"},
        {"lemma": "aequus, -a, -um", "meaning": "level, fair, equal, just"},
        {"lemma": "inīquus, -a, -um", "meaning": "uneven, unfair, unjust"},
        {"lemma": "certus, -a, -um", "meaning": "certain, sure, fixed"},
        {"lemma": "incertus, -a, -um", "meaning": "uncertain, unsure"},
        {"lemma": "vērus, -a, -um", "meaning": "true, real"},
        {"lemma": "falsus, -a, -um", "meaning": "false, fake"},
        {"lemma": "rēctus, -a, -um", "meaning": "straight, right"},
        {"lemma": "prāvus, -a, -um", "meaning": "crooked, wrong, depraved"},
        {"lemma": "dignus, -a, -um (+ abl.)", "meaning": "worthy, deserving"},
        {"lemma": "indignus, -a, -um", "meaning": "unworthy"},
        {"lemma": "cārus, -a, -um", "meaning": "dear, expensive"},
        {"lemma": "vīlis, vīle", "meaning": "cheap, worthless"},
        {"lemma": "dīves, dīvitis", "meaning": "rich, wealthy"},
        {"lemma": "pauper, pauperis", "meaning": "poor"},
        {"lemma": "fēlīx, fēlīcis", "meaning": "lucky, fortunate, happy"},
        {"lemma": "īnfēlīx, īnfēlīcis", "meaning": "unlucky, unfortunate"},
        {"lemma": "beātus, -a, -um", "meaning": "blessed, happy"},
        {"lemma": "miser, misera, miserum", "meaning": "wretched, miserable"},
        {"lemma": "fortis, forte", "meaning": "brave, strong"},
        {"lemma": "īnfirmus, -a, -um", "meaning": "weak, frail"},
        {"lemma": "validus, -a, -um", "meaning": "strong, valid"},
        {"lemma": "aeger, aegra, aegrum", "meaning": "sick, ill"},
        {"lemma": "sānus, -a, -um", "meaning": "healthy, sound"},
        {"lemma": "tūtus, -a, -um", "meaning": "safe"},
        {"lemma": "perīculōsus, -a, -um", "meaning": "dangerous"},
        {"lemma": "idōneus, -a, -um", "meaning": "suitable, fit"},
        {"lemma": "similis, simile (+ dat.)", "meaning": "similar, like"},
        {"lemma": "dissimilis, dissimile", "meaning": "unlike, different"},
        {"lemma": "quālis, quāle", "meaning": "what sort of, of what kind"},
        {"lemma": "tālis, tāle", "meaning": "such, of such a kind"},
        {"lemma": "quantus, -a, -um", "meaning": "how big, how much"},
        {"lemma": "tantus, -a, -um", "meaning": "so great, so much"},
        {"lemma": "tot (indeclinable)", "meaning": "so many"},
        {"lemma": "paucī, -ae, -a", "meaning": "few, a few"},
        {"lemma": "cēterī, -ae, -a", "meaning": "the rest, the others"},
        {"lemma": "reliquus, -a, -um", "meaning": "remaining, the rest of"},
        {"lemma": "plūres, plūra", "meaning": "more (plural)"},
        {"lemma": "ūllus, -a, -um", "meaning": "any"}
    ],
    
    "Package 8: Quality, Age & State (Adjectives II)": [
        {"lemma": "novus, -a, -um", "meaning": "new"},
        {"lemma": "antīquus, -a, -um", "meaning": "old, ancient"},
        {"lemma": "vetus, veteris", "meaning": "old"},
        {"lemma": "iuvenis, iuvenis", "meaning": "young"},
        {"lemma": "senex, senis", "meaning": "old, aged"},
        {"lemma": "recēns, recentis", "meaning": "recent, fresh"},
        {"lemma": "sacer, sacra, sacrum", "meaning": "sacred, holy"},
        {"lemma": "sānctus, -a, -um", "meaning": "holy, consecrated"},
        {"lemma": "profānus, -a, -um", "meaning": "secular, profane, unholy"},
        {"lemma": "pulcher, pulchra, pulchrum", "meaning": "beautiful, handsome"},
        {"lemma": "foedus, -a, -um", "meaning": "foul, ugly, filthy"},
        {"lemma": "turpis, turpe", "meaning": "ugly, shameful, base"},
        {"lemma": "fōrmōsus, -a, -um", "meaning": "beautiful, shapely"},
        {"lemma": "asper, aspera, asperum", "meaning": "rough, harsh"},
        {"lemma": "dulcis, dulce", "meaning": "sweet"},
        {"lemma": "amārus, -a, -um", "meaning": "bitter"},
        {"lemma": "dūrus, -a, -um", "meaning": "hard, harsh"},
        {"lemma": "mollis, molle", "meaning": "soft, gentle"},
        {"lemma": "calidus, -a, -um", "meaning": "hot, warm"},
        {"lemma": "frīgidus, -a, -um", "meaning": "cold"},
        {"lemma": "siccus, -a, -um", "meaning": "dry"},
        {"lemma": "ūmidus, -a, -um", "meaning": "wet, moist"},
        {"lemma": "albus, -a, -um", "meaning": "white (dull)"},
        {"lemma": "āter, ātra, ātrum", "meaning": "black, dark, deadly"},
        {"lemma": "niger, nigra, nigrum", "meaning": "black, glossy black"},
        {"lemma": "candidus, -a, -um", "meaning": "shining white, bright"},
        {"lemma": "ruber, rubra, rubrum", "meaning": "red"},
        {"lemma": "flāvus, -a, -um", "meaning": "yellow, blonde"},
        {"lemma": "viridis, viride", "meaning": "green"},
        {"lemma": "caeruleus, -a, -um", "meaning": "blue, sky-blue"},
        {"lemma": "aureus, -a, -um", "meaning": "golden"},
        {"lemma": "argenteus, -a, -um", "meaning": "silver, made of silver"},
        {"lemma": "ferreus, -a, -um", "meaning": "iron, made of iron"},
        {"lemma": "ligneus, -a, -um", "meaning": "wooden, made of wood"},
        {"lemma": "saxeus, -a, -um", "meaning": "rocky, made of stone"},
        {"lemma": "celer, celeris, celere", "meaning": "swift, quick"},
        {"lemma": "vēlōx, vēlōcis", "meaning": "fast, rapid"},
        {"lemma": "tardus, -a, -um", "meaning": "slow, late"},
        {"lemma": "lentus, -a, -um", "meaning": "slow, sluggish, sticky"},
        {"lemma": "sēgnis, sēgne", "meaning": "sluggish, lazy"},
        {"lemma": "laetus, -a, -um", "meaning": "happy, joyful"},
        {"lemma": "trīstis, trīste", "meaning": "sad, gloomy"},
        {"lemma": "īrātus, -a, -um", "meaning": "angry"},
        {"lemma": "placidus, -a, -um", "meaning": "calm, peaceful"},
        {"lemma": "ferōx, ferōcis", "meaning": "fierce, wild"},
        {"lemma": "saevus, -a, -um", "meaning": "savage, cruel"},
        {"lemma": "mītis, mīte", "meaning": "mild, gentle"},
        {"lemma": "crūdēlis, crūdēle", "meaning": "cruel"},
        {"lemma": "aliēnus, -a, -um", "meaning": "foreign, strange, someone else's"},
        {"lemma": "proprius, -a, -um", "meaning": "one's own, special, particular"}
    ],
    
    "Package 9: The Glue Part 1 (Adverbs)": [
        {"lemma": "haud", "meaning": "not at all, by no means"},
        {"lemma": "minimē", "meaning": "least, very little, no"},
        {"lemma": "ita", "meaning": "so, thus, in this way"},
        {"lemma": "sīc", "meaning": "thus, so, in such a way"},
        {"lemma": "tam", "meaning": "so, to such a degree"},
        {"lemma": "valdē", "meaning": "very, exceedingly"},
        {"lemma": "magis", "meaning": "more"},
        {"lemma": "maximē", "meaning": "most, especially"},
        {"lemma": "minus", "meaning": "less"},
        {"lemma": "paene", "meaning": "almost, nearly"},
        {"lemma": "ferē", "meaning": "almost, approximately"},
        {"lemma": "vix", "meaning": "scarcely, hardly"},
        {"lemma": "satis", "meaning": "enough, sufficiently"},
        {"lemma": "nimis", "meaning": "too much, excessively"},
        {"lemma": "multum", "meaning": "much, a lot"},
        {"lemma": "paulum", "meaning": "a little"},
        {"lemma": "iterum", "meaning": "again, a second time"},
        {"lemma": "rūrsus", "meaning": "back, again"},
        {"lemma": "saepe", "meaning": "often"},
        {"lemma": "numquam", "meaning": "never"},
        {"lemma": "semper", "meaning": "always"},
        {"lemma": "aliquandō", "meaning": "sometimes, at some time"},
        {"lemma": "quondam", "meaning": "once, formerly"},
        {"lemma": "ōlim", "meaning": "once upon a time, formerly"},
        {"lemma": "nūper", "meaning": "recently, lately"},
        {"lemma": "mox", "meaning": "soon"},
        {"lemma": "crās", "meaning": "tomorrow"},
        {"lemma": "hodiē", "meaning": "today"},
        {"lemma": "herī", "meaning": "yesterday"},
        {"lemma": "statim", "meaning": "immediately, at once"},
        {"lemma": "prōtinus", "meaning": "straightaway, immediately"},
        {"lemma": "tandem", "meaning": "finally, at last"},
        {"lemma": "deinde", "meaning": "then, next"},
        {"lemma": "deinceps", "meaning": "in turn, successively"},
        {"lemma": "posteā", "meaning": "afterward, later"},
        {"lemma": "praetereā", "meaning": "besides, moreover"},
        {"lemma": "anteā", "meaning": "before, previously"},
        {"lemma": "ubi", "meaning": "where, when"},
        {"lemma": "quō", "meaning": "where to, to what place"},
        {"lemma": "unde", "meaning": "from where, whence"},
        {"lemma": "quā", "meaning": "by which route, where"},
        {"lemma": "hīc", "meaning": "here, in this place"},
        {"lemma": "hūc", "meaning": "to here, hither"},
        {"lemma": "hinc", "meaning": "from here, hence"},
        {"lemma": "ibi", "meaning": "there, in that place"},
        {"lemma": "illīc", "meaning": "there, in that place (yonder)"},
        {"lemma": "bene", "meaning": "well"},
        {"lemma": "male", "meaning": "badly"},
        {"lemma": "subitō", "meaning": "suddenly"},
        {"lemma": "tamen", "meaning": "however, nevertheless"}
    ],
    
    "Package 10: The Glue Part 2 (Preps, Conjunctions & Questions)": [
        {"lemma": "prō (+ abl.)", "meaning": "for, on behalf of, in front of"},
        {"lemma": "prae (+ abl.)", "meaning": "before, in front of"},
        {"lemma": "sub (+ acc. / + abl.)", "meaning": "under, beneath"},
        {"lemma": "super (+ acc. / + abl.)", "meaning": "above, over"},
        {"lemma": "suprā (+ acc.)", "meaning": "above, beyond"},
        {"lemma": "trāns (+ acc.)", "meaning": "across, over"},
        {"lemma": "ob (+ acc.)", "meaning": "because of, on account of"},
        {"lemma": "propter (+ acc.)", "meaning": "because of, on account of"},
        {"lemma": "circum (+ acc.)", "meaning": "around"},
        {"lemma": "inter (+ acc.)", "meaning": "between, among"},
        {"lemma": "intrā (+ acc.)", "meaning": "within, inside"},
        {"lemma": "extrā (+ acc.)", "meaning": "outside, beyond"},
        {"lemma": "apud (+ acc.)", "meaning": "at the house of, near, among"},
        {"lemma": "autem", "meaning": "however, moreover"},
        {"lemma": "vērum", "meaning": "but, however, in truth"},
        {"lemma": "at", "meaning": "but, but yet"},
        {"lemma": "enim", "meaning": "for, indeed"},
        {"lemma": "nam", "meaning": "for"},
        {"lemma": "quia", "meaning": "because"},
        {"lemma": "quod", "meaning": "because, that"},
        {"lemma": "quoniam", "meaning": "since, inasmuch as"},
        {"lemma": "sī", "meaning": "if"},
        {"lemma": "nisi", "meaning": "unless, if not, except"},
        {"lemma": "etsī", "meaning": "even if, although"},
        {"lemma": "quamquam", "meaning": "although"},
        {"lemma": "quamvīs", "meaning": "however much, although"},
        {"lemma": "postquam", "meaning": "after"},
        {"lemma": "antequam", "meaning": "before"},
        {"lemma": "ut", "meaning": "so that, in order that, as"},
        {"lemma": "nē", "meaning": "lest, so that not"},
        {"lemma": "cūr", "meaning": "why"},
        {"lemma": "quandō", "meaning": "when"},
        {"lemma": "quōmodo", "meaning": "how"},
        {"lemma": "quis", "meaning": "who"},
        {"lemma": "quid", "meaning": "what"},
        {"lemma": "quot", "meaning": "how many"},
        {"lemma": "quantus, -a, -um", "meaning": "how big, how much"},
        {"lemma": "quālis, quāle", "meaning": "what sort of"},
        {"lemma": "uter, utra, utrum", "meaning": "which (of two)"},
        {"lemma": "neuter, neutra, neutrum", "meaning": "neither"},
        {"lemma": "alter, altera, alterum", "meaning": "the other (of two)"},
        {"lemma": "-ne (enclitic)", "meaning": "indicates a yes/no question"},
        {"lemma": "nōnne", "meaning": "surely (expects a yes answer)"},
        {"lemma": "num", "meaning": "surely not (expects a no answer)"},
        {"lemma": "aliquis, aliquid", "meaning": "someone, something"},
        {"lemma": "quīdam, quaedam, quoddam", "meaning": "a certain, some"},
        {"lemma": "quisque, quidque", "meaning": "each one, everyone"},
        {"lemma": "īdem, eadem, idem", "meaning": "the same"},
        {"lemma": "quīcumque, quaecumque, quodcumque", "meaning": "whoever, whatever"},
        {"lemma": "ipse, ipsa, ipsum", "meaning": "himself, herself, itself (intensive)"}
    ]
}
